### ISSUE TITLE
JSON Documentation Discovery

### ISSUE THREAD

**Issue by kidehen** [CLARIAH/grlc#122]
How do I find the URI that identifies the JSON rendition of the OpenAPI documentation for each API produced by your solution? Ideally, you would have an icon placed somewhere in the HTML-based interaction console [1] combined with other discovery techniques such as the <script/> script or @rel in HTML and HTTP respectively. 

[1] https://osdb.openlinksw.com/osdb/api/console

**Comment by c-martinez** [comment]
JSON representation of `http://grlc.io/api/albertmeronyo/lodapi/` can be found here `http://grlc.io/api/albertmeronyo/lodapi/spec` -- is this what you are referring to?

Yes, other discovery techniques would be nice. Grlc is using a relatively old version of swagger-ui, as pointed out by issue #105 -- so it is definitely an improvement which should be implemented. Pull requests on this direction would be very welcome!

**Comment by kidehen** [comment]
@c-martinez ,

This relates to bug at: https://github.com/CLARIAH/grlc/issues/64 .

**Comment by c-martinez** [comment]
@kidehen -- #123 has now been merged (although not yet deployed at `grlc.io`). Do you have a local grlc instance where you could check if this meets requirements for JSON discovery ? If not, we might need to wait until it is deployed and we can then check and see if we can close this issue.

**Comment by kidehen** [comment]
@c-martinez ,

I don't have a local instance, so just notify me when its deployed publicly and I can then repeat my tests.

**Comment by albertmeronyo** [comment]
Hi @kidehen @c-martinez thanks for looking into this.
I deployed but rolled back, since I spotted a number of bugs I did not catch before the merge. Hopefully we can re-deploy soon.

**Comment by c-martinez** [comment]
@kidehen -- we now have a `dev.grlc.io` version deployed, which uses a more recent version of SwaggerUI. When you load, for instance `http://dev.grlc.io/api/albertmeronyo/lodapi`, this version provides already a link to `/api/albertmeronyo/lodapi/spec` at the top. 

Could you check it out and let us know if this already what you expected? We can then close this issue.

**Comment by c-martinez** [comment]
Closing issue -- please re-open if the solution does not really solve the issue.
