### ISSUE TITLE
Unused `addApiKeyAuthorization`

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/grlc#124]
@albertmeronyo -- is this code used:

https://github.com/CLARIAH/grlc/blob/master/src/templates/api-docs.html#L93-L108

When loading `http://grlc.io/api/albertmeronyo/lodapi` it is throwing:

```
lodapi:94 Uncaught TypeError: Cannot read property 'value' of undefined
    at addApiKeyAuthorization (lodapi:94)
```

I think it is because `input_apiKey` does not exist. I think it is unused code and could be removed.

**Comment by albertmeronyo** [comment]
Thanks @c-martinez for catching this. I think it's old code for passing the Swagger validation; possibly related to #64 
But indeed should be safe to remove for now
