### ISSUE TITLE
Option to select 'all values' for parameters 

### ISSUE THREAD

**Issue by AshkanA** [CLARIAH/grlc#13]
So users can query for all **years** or all **municipalities**

**Comment by RinkeHoekstra** [comment]
This is an understandable request, but it is not going to happen in grlc for a number of (mostly technical) reasons: incompatibility with Swagger API spec (you're dynamically adding another response field), and there could be a perfectly valid value 'all' in your database that you would like to constrain the results to.

**Comment by albertmeronyo** [comment]
This turns to be a requirement better addressed by writing another query in CEDAR-project/Queries, so closing this one and opening a new one there.
Thanks @AshkanA !
