### ISSUE TITLE
validation error in OpenAPI UI for string literals

### ISSUE THREAD

**Issue by egonw** [CLARIAH/grlc#136]
I have created a [demo API for WikiPathways](https://github.com/egonw/wp-rdf-api) where I am trying to use a `xsd:string` literal parameter. In the SPARQL, the typing is important, because without the explicit typing, Virtuoso does not result any data... but that's not the problem... the OpenAPI GUI currently gives me a validation error...

So, I have the following annotated SPARQL:

```SPARQL
#+ summary: Get Curation Tags
#+ endpoint_in_url: False
#+ endpoint: http://query.wikidata.org/sparql
#+ tags:
#+   - Pathway information
#+ enumerate:
#+   - pwId

PREFIX wp:      <http://vocabularies.wikipathways.org/wp#> 
PREFIX dc:      <http://purl.org/dc/elements/1.1/> 
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/> 
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>

SELECT
 (substr(str(?ontTag), 41) AS ?pwOntologyTerm)
 (str(?titleLit) AS ?title)
 ?pathway 
WHERE {
  ?pathwayRDF wp:ontologyTag ?ontTag ;
    foaf:page ?pathway ;
    dc:title ?titleLit ;
    dcterms:identifier ?_pwId_string . 

  FILTER (!regex(str(?pathway), "group"))
  FILTER ( regex(str(?ontTag), "vocabularies.wikipathways"))
}
```

Debug info from `grlc` suggests it is picked up as expected (with slight editing for readability):

```
'parameters': {                              
u'pwId': {
  'datatype': 'xsd:string',
  'enum': [                               ],
  'lang': None,
  'name': u'pwId',
  'original': '?_pwId_string',
  'required': True,
  'type': 'literal'}},
```

And the parameter also shows up in the OpenAPI GUI properly (the new one? the layout changed in the last few weeks, it seems), but when I try to execute the method with the string `WP1425`, it shakes the input box (not shown, it's a static image :) and colors red (shown):

![image](https://user-images.githubusercontent.com/26721/43904219-6bc46d2a-9bee-11e8-81ff-96849a45c399.png)

Any help, even on how to further debug this, most appreciated!

**Comment by c-martinez** [comment]
Indeed this is a bug -- PR #135 should fix it.

In the mean time, as a workaround: if change your variable to `?_pwId`, then the type should default to `string` and you should be able to get through validation.

**Comment by egonw** [comment]
I think I'll wait for the PR, because with just `?_pwId` the SPARQL does not match the explicitly typed RDF structure (which I guess it actually should...)
