### ISSUE TITLE
Query parsing is odd when OPTIONAL contains parameters

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/grlc#14]
The OPTIONAL clause is not parsed correctly by the parameter matchers (seems to be just discarded from the query included in the spec)

**Comment by c-martinez** [comment]
Some [complicated](https://github.com/DivePlus/queries/blob/master/getSearchQuery.rq) [queries](https://github.com/DivePlus/queries/blob/master/relatedAction.rq) with `OPTIONAL` clauses seem to be parsed incorrectly.

As a work around, is there a way to tell grlc to *not* try to generate enums for certain parameters? for example if they are `?_name_string`

**Comment by albertmeronyo** [comment]
I agree that grlc shouldn't try to fill in enums for all parameters: it's expensive, and not very useful if the variable is bound to a large number of values. 
On the other hand, it's hard to foresee whether iri, literal or other kinds of parameters should get enums or not. E.g. some ?_var_string might be bound to a few distinct literals, and an enum might still be useful.

I think what's best here is to let users decide, so I implemented this in 191a83f
By default, parameters will get no enums. If the name of that parameter (with no ?, _, __ or _iri/_label additions) is present in a #+ enumerate: -var1 -var2 metadata, then the enum will be generated for that parameter (see a working example in https://github.com/CEDAR-project/Queries/blob/master/houseType_params.rq).

**Comment by RinkeHoekstra** [comment]
... wouldn't it be more natural to extend the variable labelling with an enum parameter? E.g. `?_example_iri_enum`

#justsayin

**Comment by c-martinez** [comment]
I think the generating enums on demand (only for parameters which explicitly request it), is a more elegant solution. You are right, @albertmeronyo in that a string might still require an enum.

As for labeling the parameter itself, it might get tricky with different combinations, e.g: `?_name`, `?_name_string`, `?_name_enum`, `?_name_string_enum`, `?_name_prefix_datatype`, `?_name_prefix_datatype_enum`, etc.

**Comment by c-martinez** [comment]
I believe this is fixed with the `enumerate` key word on the grlc header. Closing.
