### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/grlc#141]
We should have a tutorial showing:
 - How to use grlc as webservice
 - How to use grlc from a notebook

**Comment by albertmeronyo** [comment]
Working on it [here](https://github.com/CLARIAH/grlc/wiki/Quick-tutorial)

**Comment by albertmeronyo** [comment]
I just finished the [quick tutorial](https://github.com/CLARIAH/grlc/wiki/Quick-tutorial) @c-martinez @rlzijdeman Do you want to have a look?

I'm updating the list of tutorials since the previous one shows the need for more :)

- How to use grlc as webservice <-- @c-martinez I don't remember what we meant by this, can you refresh my memory? :)
- How to use grlc from a notebook
- How to use all query decorators
- How to map query variables to HTTP request parameters

**Comment by c-martinez** [comment]
Hey @albertmeronyo -- nice work! I'll have a look later this week.

I think by 'grlc as a webservice' we meant executing a SPARQL query by calling a url: `http://grlc.io/api/albertmeronyo/my-linked-data-api/myquery?endpoint=http%3A%2F%2Fdbpedia.org%2Fsparql` 

And by 'grlc from a notebook' we meant executing a SPARQL query bg doing something like
```python
import grlc
myrepo = grlc('user', 'repo')
result = myrepo.execute('my-linked-data-api')
```
this is not quite the correct syntax, but that is the idea.
(both can be done on a notebook of course).

If you work on the first part (webservice) I can work on the second (notebook). Would that be a good plan?

**Comment by albertmeronyo** [comment]
Absolutely! In the tutorial there's already some indications on [how to use grlc as a webservice](https://github.com/CLARIAH/grlc/wiki/Quick-tutorial#using-your-linked-data-api) but I'm pretty sure it can be extended and show more technical detail. So maybe a link from that page to the one you'll write :-)

I'm very happy to write about notebooks (have to implement them anyway soon), so I'll take care of that

**Comment by c-martinez** [comment]
@albertmeronyo -- I put together a notebook which uses grlc from python:

https://github.com/CLARIAH/grlc/blob/dev/GrlcFromNotebook.ipynb

Probably not the best place to put it, so we should move it somewhere that makes sense.

**Comment by albertmeronyo** [comment]
Fantastic, thanks for this @c-martinez ! 

I'll move it to doc/notebooks for the time being, and if it grows too much we can always start a new repo.
This is probably just for myself to remember but nice follow up steps could be:
- Add a page/link/description to the documentation in the wiki
- Add a few [HTML widgets](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html) so the collection of input values (user, repo, content type, call params, etc.) are more user friendly from within the notebook

**Comment by c-martinez** [comment]
Perfect -- thanks @albertmeronyo !

**Comment by c-martinez** [comment]
Added an extra example [here](https://github.com/CLARIAH/grlc/wiki/Quick-tutorial#using-grlc-from-python) -- with that and the recent addition of linked data fragments to the tutorial, I think we can close this issue.
