### ISSUE TITLE
add parameter examples in lodapi example api

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/grlc#148]

**Comment by vemonet** [comment]
This would be really interesting! Because at the moment finding how grlc parameters works is really difficult. A lot of different implementations at different places that doesn't work
And an API without parameters is pointless

**Comment by vemonet** [comment]
Apparently the parameters are not working anymore

I managed to make this query worked 1 month ago: http://grlc.io/api/vemonet/ncats-grlc-api#/
https://github.com/vemonet/ncats-grlc-api/blob/master/get_drugs_for_gene.sparql

If I add the "enumerate" part the call simply disappear from the swagger UI spec.

But without the enumerate I can use the parameters (using "HGNC:3535" for instance). But I got a `TypeError: NetworkError when attempting to fetch resource.`
Maybe I should add a suffix to specify it is a string? But last time it was working without suffix

**Comment by albertmeronyo** [comment]
Hi @vemonet , thanks for reporting these!

This might well have to do with the latest commits, so let's see if we can find the bug. Could you try these two things?

- I noticed that at https://github.com/vemonet/ncats-grlc-api/ you have `.rq` and `.sparql` versions of the same API method. This might be confusing grlc, since both extensions are processed but only one makes it to the final spec. Could you try renaming them? (or just stick to one)
- In the version in which you're using `#+ enumerate:`, try to specify the values of the enumeration like this:

```
#+ enumerate:
#+   - geneId
#+      - myValue1
#+      - myValue2
```

For queries that do not use enum the parameter mapping should work just fine for both URIs and literals.
Thanks,
Albert

**Comment by albertmeronyo** [comment]
I've fixed a number of issues regarding parameter enumerations, and added the lodapi parameter example (with pre-filled enumerations) at http://grlc.io/api/albertmeronyo/lodapi/#/SPARQL/get_houseType_params

@vemonet let me know if this helps with your issue

**Comment by c-martinez** [comment]
New [examples repo](https://github.com/CLARIAH/grlc-queries/) has examples an example of `enumerate` decorator. Hopefully that solves this issue.

Closing.
