### ISSUE TITLE
Adequate processing of optional parameters

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/grlc#15]
When a parameter is optional, grlc should:
- If it has a value, rewrite query to replace variable name with value
- If it has not a value, don't rewrite anything

**Comment by albertmeronyo** [comment]
Side effect: if the parameter is optional, and the variable of that parameter appears as a projection, and the user DOES give it a value, then rewrite query removing the variable name from the projection

**Comment by c-martinez** [comment]
@albertmeronyo -- I am not sure what this issue was about, but it is super old.

I will close it and, if still relevant, please open it again and add more details of what it is about.
