### ISSUE TITLE
Swagger-ui does not validate parameter types correctly

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/grlc#150]
For API methods that have an IRI 
argument that is required, for example

- http://grlc.io/api/peta-pico/nanopub-api/#/default/get_get_nanopub
- 
http://grlc.io/api/peta-pico/nanopub-api/#/default/get_find_nanopubs_with_uri

the user interface complains about the required argument (marks it in 
red) and doesn't allow me to execute the query even after entering a 
fully valid IRI.

**Comment by c-martinez** [comment]
Seems like swagger data-types does not validate IRI's: https://swagger.io/specification/v2/

It might work to replace 
```
type: iri
```

For something like:
```
type: string
format: iri
pattern: 'http[s]*://'
```
But then we need a regex pattern for validating iri's (or leaving it blank and allow anything). I would be inclined to do that and just make it the user's responsibility to provide a valid IRI.

**Comment by rlzijdeman** [comment]
Hi @c-martinez, this is a bit of a shot in the dark, but would this be of help?
https://github.com/CLARIAH/iribaker

**Comment by c-martinez** [comment]
Long shot indeed. `iribaker` is not directly what we need, but we could

 - Modify `iribaker` to have a validate function (it already does but we could modify it to be able to use it externally
 - Add iri validation to `grlc` (I believe we can change the swagger specification so that it uses a validation endpoint).

The question is: is it crucial for grlc to validate iri's? Is it a nice-to-have? Is it completely out of scope? @albertmeronyo -- what do you think?

**Comment by rlzijdeman** [comment]
"It's not directly what we need" -> provides enough reason not to use it :)

**Comment by albertmeronyo** [comment]
Thanks @c-martinez @rlzijdeman for your suggestions!
I agree that iribaker does not directly solve the problem, but might give us directions into how to solve it.

For the time being I would just
- leave iris as strings as per @c-martinez suggestion, but I wouldn't add any additional validation requirements (we might end up implementing the whole RFC :-) ).
- look into openAPI's documentation for common datatypes/iris, or find a real world openAPI spec that validates them correctly

**Comment by albertmeronyo** [comment]
Fixed this in dev.grlc.io as per @c-martinez suggestion. A parameter's `type` should never be 'iri' anyways (MUST be one of "string", "number", "integer", "boolean", "array" or "file" as per https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject), so now SPARQL variables that should be replaced by IRIs are specified as parameters with

`
type: string
format: iri
` 

(format is an open value)
There's a bit of extra processing in the query rewriter that looks into `format` in order to properly replace literal and iri parameters when the query is executed
