### ISSUE TITLE
where do I find documentation on which tags i can use?

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/grlc#161]

**Comment by c-martinez** [comment]
Hi @rlzijdeman ,

Do you mean in the query decorators? 
```
#+ tags:
#+   - dbpedia
```

These tags are completely arbitrary -- so you can add whichever tags you want and as many of them as you see fit.

**Comment by c-martinez** [comment]
Good question -- there isn't any good documentation for it. But @albertmeronyo has been working on writing a [tutorial](https://github.com/CLARIAH/grlc/wiki/Quick-tutorial) which will explain all of them. And it will be ready... soon.

**Comment by rlzijdeman** [comment]
thanks @albertmeronyo @c-martinez https://github.com/CLARIAH/grlc/wiki/Query-decorators
