### ISSUE TITLE
Possibility to load queries from file

### ISSUE THREAD

**Issue by dgarijo** [CLARIAH/grlc#162]
Hello,
the current documentation covers how to set up GRLC with a Github repo, but not how to feed directly the files with my queries. Is this possible if I set up my server?
Thanks in advance!

**Comment by albertmeronyo** [comment]
Hi @dgarijo ,

Yes, this is definitely possible, and you're right the documentation doesn't help much (we're working on it in the wiki). There are two things to set up:
- the local path where grlc will search for your queries in [config.ini](config.ini)
- to call the API spec generation, go to http://localhost:port/api/local/local

Please let us know if this works fine for you

**Comment by dgarijo** [comment]
I see, thanks!
