### ISSUE TITLE
Parameters are not editable in the GUI

### ISSUE THREAD

**Issue by dgarijo** [CLARIAH/grlc#163]
None of the string parameters are editable anymore on the GUI. See: 
http://grlc.io/api/albertmeronyo/lodapi/#/default/get_houseType_params

This is a little tragic, as no one can play with their values anymore :(

**Comment by albertmeronyo** [comment]
Thanks @dgarijo for spotting this! I just fixed and redeployed, parameters should be back to normal now. Please let me know otherwise

**Comment by dgarijo** [comment]
It works perfectly, thanks!! And thanks to you and your team for grlc :)
