### ISSUE TITLE
Set default parameter values

### ISSUE THREAD

**Issue by dgarijo** [CLARIAH/grlc#164]
I have noticed that there are ways of specifying hardcoded values for parameters, but it would be great if you could specify default values in the swagger document for parameters like ?_var_iri. That way you would have an example of use on the documentation of the API call.

**Comment by albertmeronyo** [comment]
Implemented in edf64123cd4e567613ca15deb03b2caf892c3bb2

See example at http://grc.io/api/albertmeronyo/lodapi/#/dbpedia/get_dbpedia_test from the query at https://github.com/albertmeronyo/lodapi/blob/master/dbpedia_test.rq making use of the decorator

```
defaults:
  - param_name: default_value
```

Thanks for reporting @dgarijo ! :-)

**Comment by dgarijo** [comment]
Will give it a try, thanks!!!!
