### ISSUE TITLE
Parse folders of repository

### ISSUE THREAD

**Issue by dgarijo** [CLARIAH/grlc#165]
I have added a repository where the queries are in a folder. GRLC doesn't create any API for it. I haven't seen a way of configuring this.

**Comment by c-martinez** [comment]
This is not currently supported -- it has been on the list of features to implement for a long time (see #24). Should not be difficult to implement, but it has been very low in the priority list.

**Comment by dgarijo** [comment]
I see, thanks for the heads up. I look forward to having this feature, as now I have to separate the queries into a separate repository :)

**Comment by c-martinez** [comment]
I'll close this issue and leave #24 open, but we should bump it up in priority.

**Comment by albertmeronyo** [comment]
Reopening -- Just got another request for having this so assigning higher priority.
Will try to drop some commits under dev to test it

**Comment by albertmeronyo** [comment]
Just added a first implementation for this, with three important limitations:

- Only applies to queries stored in GitHub
- Supports only subdirs at 1 level of depth
- The API spec has some ambiguous clashes, so it will need refactoring but for now making sure to append a slash `/` every time you require an API spec (and not a query call) should be fine

Should be shortly available at dev.grlc.io. Please let us know if there's any issue!

**Comment by c-martinez** [comment]
This should now be possible using the `subdir` [option](https://github.com/CLARIAH/grlc#from-a-github-repository).

Closing this issue, if this does not fix your issue, please reopen.
