### ISSUE TITLE
warning on no prefixes listed

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/grlc#168]
Hi, if prefixes are missing in the .rq file, and uri's are not fully specified, no API is generated for the specific query. Obviously, that is correct behaviour, but a warning indicating that the user might have forgotten prefixes would be nice. Issue mentioned by @biktorrr and  @RoderickvanderWeerdt

**Comment by c-martinez** [comment]
Fixed in v1.3.5 -- only took a year ;-) Thank you for your patience!
