### ISSUE TITLE
Enable content negotiation via URL

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/grlc#17]
So that this:

http://localhost:8088/CEDAR-project/Queries/residenceStatus_all.csv

Calls the operation 'residenceStatus' using the HTTP header "Accept: text/csv"

**Comment by LaurensRietveld** [comment]
A comment on the content negotiation. When you map the extension to the accept headers, make sure that .json does not only get mapped to 'application/json', but also to 'application/sparql-results+json'. The same goes for xml. And, fingers crossed that the endpoint does support actual content negotiation on e.g. `application/json; q=1.0, application/sparql-results+json; q=0.8`, and not does simple string matching that expects a single content-type (I know some endpoints do ;))
