### ISSUE TITLE
Dropping Python2 support

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/grlc#178]
Python 2.7 will not be maintained past [January 1st 2020](https://pythonclock.org/) -- we should make sure grlc is not only Python 3 compatible, but fully migrated.

**Comment by albertmeronyo** [comment]
Excellent point @c-martinez This just came to my attention too
@pasqlisena just made some useful comments - e.g. we're still using the Python 2.7 Docker image as a basis

**Comment by albertmeronyo** [comment]
If we merge `python3` into `master` this will be solved right @c-martinez ?

**Comment by c-martinez** [comment]
Yes -- I would even say we should merge `dev`. I'll send a PR.
