### ISSUE TITLE
docker build of latest commit leads to error: "Sphinx requires at least Python 3.5 to run"

### ISSUE THREAD

**Issue by tkuhn** [CLARIAH/grlc#181]
I get the following error when trying to build the docker container:

> Processing /home/grlc/grlc
>     Complete output from command python setup.py egg_info:
>     zip_safe flag not set; analyzing archive contents...
>     
>     Installed /tmp/pip-5OdB68-build/.eggs/recommonmark-0.5.0-py2.7.egg
>     Searching for sphinx
>     Reading https://pypi.python.org/simple/sphinx/
>     Downloading https://files.pythonhosted.org/packages/ac/bd/c7406eeb5ba234237ff67718d8f7805b320a917a74a6cc7ba52a4f50ff4c/Sphinx-2.0.0b1.tar.gz#sha256=230af939a2f678ab4f2a0a948c3b24a822a0d280821859caaefb750ef7413003
>     Best match: Sphinx 2.0.0b1
>     Processing Sphinx-2.0.0b1.tar.gz
>     Writing /tmp/easy_install-vS_Nex/Sphinx-2.0.0b1/setup.cfg
>     Running Sphinx-2.0.0b1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vS_Nex/Sphinx-2.0.0b1/egg-dist-tmp-BvaCMe
>     ERROR: Sphinx requires at least Python 3.5 to run.
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-5OdB68-build/setup.py", line 50, in <module>
>         package_data = {'grlc': grlc_data},
>       File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup
>         _setup_distribution = dist = klass(attrs)
>       File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 316, in __init__
>         self.fetch_build_eggs(attrs['setup_requires'])
>       File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 371, in fetch_build_eggs
>         replace_conflicting=True,
>       File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
>         dist = best[req.key] = env.best_match(req, ws, installer)
>       File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1118, in best_match
>         return self.obtain(req, installer)
>       File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1130, in obtain
>         return installer(requirement)
>       File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 439, in fetch_build_egg
>         return cmd.easy_install(req)
>       File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
>         return self.install_item(spec, dist.location, tmpdir, deps)
>       File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
>         dists = self.install_eggs(spec, download, tmpdir)
>       File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
>         return self.build_and_install(setup_script, setup_base)
>       File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
>         self.run_setup(setup_script, setup_base, args)
>       File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
>         raise DistutilsError("Setup script exited with %s" % (v.args[0],))
>     distutils.errors.DistutilsError: Setup script exited with 1
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-5OdB68-build/
> You are using pip version 9.0.1, however version 19.0.2 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> ERROR: Service 'grlc' failed to build: The command '/bin/sh -c bash ${GRLC_BUILD_DIR}/install.sh' returned a non-zero code: 1

**Comment by albertmeronyo** [comment]
Thanks for this @tkuhn 
We're working on this at af9eb6b

Related issue #178

**Comment by c-martinez** [comment]
Image `clariah/grlc:python3` solves this issue.
