### ISSUE TITLE
config.ini overridden with config.default.ini even if config.ini is already present

### ISSUE THREAD

**Issue by tkuhn** [CLARIAH/grlc#183]
It seems config.ini is overridden with config.default.ini even if the former is already present. Concretely, I did these steps:

    $ docker pull clariah/grlc:latest
    $ docker-compose up -d
    $ docker cp config.ini d3b15398a5f2:home/grlc/grlc/

(and checking with `docker exec -it CONTAINERID bash` that the file is now indeed there)

This doesn't seem to take effect immediately, which makes sense, so restarting:

   $ docker-compose stop
   $ docker-compose start

Accessing the service shows that config.ini is not applied, and doing `docker exec -it CONTAINERID bash` again confirms that the file is overridden with the content of config.default.ini.

The workaround is to change config.default.ini too:

    $ docker cp config.ini d3b15398a5f2:home/grlc/grlc/config.default.ini

**Comment by c-martinez** [comment]
Hey @tkuhn, is there any particular reason you need a custom config.ini? `server_name` and `github_access_token` can be configured via env variables to your docker image:

```
docker run --rm -p 8088:80 -e GRLC_SERVER_NAME=grlc.io -e GRLC_GITHUB_ACCESS_TOKEN=xxx -e DEBUG=true clariah/grlc
```

and I'm working on having `sparql_endpoint` also as env variable.

Are you after configuring something different?

**Comment by tkuhn** [comment]
I need it to set `local_sparql_dir` to read local files instead of connecting to GitHub.

**Comment by c-martinez** [comment]
`local_sparql_dir` is set to reading files from `./`, which I assume would be `/home/grlc` inside the container. Maybe we can set it to `/home/grlc/queries` by default, and then if you copy your queries there, you won't need to set anything up via config. Would that work?

**Comment by tkuhn** [comment]
Yes, I think so! Then I would mount `/home/grlc/queries` as a volume via docker, right?

**Comment by c-martinez** [comment]
Yes -- I'll do that and let you know when it is on dockerhub.

**Comment by tkuhn** [comment]
OK, that'd be great, thanks!

**Comment by c-martinez** [comment]
Can you try now using image `clariah/grlc:dev` ? If this works we can close this issue.

**Comment by tkuhn** [comment]
Hm, doesn't seem to work. I have the api repo files mounted at `/home/grlc/queries` and I checked that these files are really there from inside the container, but accessing it via `http://localhost:8001/api/local/local` gives "No operations defined in spec!".

**Comment by c-martinez** [comment]
Looking into it...

**Comment by c-martinez** [comment]
I think there was an issue with a python dependency. A new image has been built, can you check again?

**Comment by tkuhn** [comment]
Still doesn't work...

**Comment by c-martinez** [comment]
Could you share the docker command you are using to run the container? I'll try to debug it locally.

I suspect it might be that `/home/grlc/queries` needs to be `/home/grlc/queries/` in config.default.ini (which would indicate a different bug). But I would like to test it before wasting your time with "try again"

**Comment by tkuhn** [comment]
I am using docker-compose like this:

```
version: '2'
services:
  grlc:
    image: clariah/grlc:dev
    restart: unless-stopped
    ports:
     - 8001:80
    environment:
     - DEBUG=true
     - USERMAP_GID=1000
     - USERMAP_UID=1000
    volumes:
     - ./data/grlc/nanopub-api:/home/grlc/queries
```

**Comment by c-martinez** [comment]
Thanks for that. I think indeed that was a bug. I've created a new image -- can you do `docker pull clariah/grlc:dev` and try again?

**Comment by tkuhn** [comment]
Yes, it works now! :) Thanks a lot!

**Comment by c-martinez** [comment]
Great! Glad it works :-)
