### ISSUE TITLE
Can't install with pipenv using Python 3.7

### ISSUE THREAD

**Issue by jblom** [CLARIAH/grlc#197]
I'm now migrating our search API with grlc support from Python 2.7 to Python 3.7, but (using pipenv) I get errors when installing the greenlet & gevent packages:

"An error occurred while installing gevent==1.1.2"
"An error occurred while installing greenlet==0.4.10"

**How to reproduce**:

Run in a terminal on macOS High Sierra:

`
pipenv --python 3.7
pipenv shell
pipenv install grlc
`

Is grlc compatible with another Python 3.x version?

**Comment by mwigham** [comment]
It looks like this has been solved in the code in github, but not yet updated on pypi, could that be?

For now, I found a workaround using the following steps:

- download grlc from github
- In setup.py, replace the n with a trema with a standard n (sorry Albert!)
- in sparql.py, replace iteritems() with items()
- Delete the contents of readme.md
- (optional: activate my virtual environment)
- In grlc-master: python setup.py install
- pip install static

**Comment by jblom** [comment]
@mwigham thanks, but really hoping for the fix in pypi, since it needs to be automatically installed and would like to avoid writing a special script for this.

@c-martinez could you help us out?

**Comment by mwigham** [comment]
As I used the latest version of grlc in my download, I guess that means the iteritems in sparql.py will also need fixing before the pypi is updated.

**Comment by c-martinez** [comment]
Hi @jblom & @mwigham for reporting this. In principle, grlc should be python 3 compatible, but you are right, current version is broken.

There seem to be a few issues in the current version since builds on Travis are also failing -- it seems to be related to SPARQLTransform ?

@albertmeronyo -- do you have some time to look into this? I'll try to have a look as well.

@jblom / @mwigham -- if you have some time and are willing to help, PR's would be very welcome ;-)

**Comment by mwigham** [comment]
@c-martinez  I have changes ready to check in. Which branch is it best to use? Then I can create a PR

**Comment by albertmeronyo** [comment]
Thanks @mwigham and @jblom for noticing and contributing to this! PRs to branch dev are automatically built and deployed so I'd advice sending it there -- thanks!

**Comment by jblom** [comment]
@albertmeronyo @c-martinez just curious to hear when the fix will be in the new release. If I'm correct this has already been fixed in the dev branch?

**Comment by c-martinez** [comment]
Hi @jblom -- yes, all tests are currently passing on `dev` branch. I am just giving some time to @albertmeronyo to review the changes and then merge.

**Comment by jblom** [comment]
@c-martinez awesome thanks for the quick response :-)

for context: if the fix is there we can deploy our awesome local grlc experiments on the server (without hacking there)

**Comment by c-martinez** [comment]
Hey @jblom, @mwigham -- grlc 1.3.0 is out and is fully python3 compatible! I hope this solves your issue :-)

**Comment by mwigham** [comment]
Great news! Thank you very much. I'll have a go at testing it.

**Comment by jblom** [comment]
Hey @c-martinez, the issue with installing grlc seems to be gone! (at least locally) Now to test it on the server and all should be good :))

**Comment by c-martinez** [comment]
Perfect -- I'll close this issue then :-)
