### ISSUE TITLE
v1.3 release in pypi

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/grlc#198]
Hi @c-martinez ! I know you've taken care of uploading the previous releases to pypi. Could you do as much for v1.3? Not urgent but would be good. Thanks!

**Comment by c-martinez** [comment]
Hi @albertmeronyo -- tests on travis are failing, so I haven't made a new release yet. I would like to fix that first.

**Comment by c-martinez** [comment]
Released!

**Comment by rlzijdeman** [comment]
Congratulations 🎉🎈🍾!!!

On 1 Jul 2019, at 14:12, Carlos Martinez <notifications@github.com<mailto:notifications@github.com>> wrote:


Released!
