### ISSUE TITLE
Parameters do no work with FILTER clause

### ISSUE THREAD

**Issue by arnikz** [CLARIAH/grlc#201]
I'd like do some filtering on the result set using a set of parameters. SPARQL (range) queries that include the parameters in the `FILTER` clause do not work. For example, the `age` does not show up in the UI:

```
#+ defaults:
#+  - age: 20
...
FILTER(?age > ?_age_integer)
```

**Comment by c-martinez** [comment]
This was solved by adding an outer block `{}`. See [this issue](https://github.com/candYgene/queries/issues/12) for more info.
