### ISSUE TITLE
Use patches on tests

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/grlc#207]
The `test_sparql_transformer` test, relies on response from `dbpedia`:

https://github.com/CLARIAH/grlc/blob/f5664e34f039010c00ef8ebb69917c05e8ce75d7/tests/test_gquery.py#L208-L219

This means that if you are not connected to the internet, it is not possible to run this test. One way to work around this is to use `@patch` (as done in [test_get_enumeration](https://github.com/CLARIAH/grlc/blob/f5664e34f039010c00ef8ebb69917c05e8ce75d7/tests/test_gquery.py#L65) test) to mock the http request.

@pasqLisena -- could you possibly have a look at this test?

**Comment by pasqLisena** [comment]
Hi @c-martinez . I can give a look to this next week.

**Comment by c-martinez** [comment]
Closed by #216
