### ISSUE TITLE
error when using latest dev Docker container with local/local

### ISSUE THREAD

**Issue by tkuhn** [CLARIAH/grlc#208]
I get the follwing error with the latest dev Docker version, when using with local SPARQL files in `/home/grlc/queries/` and accessing them via `api/local/local`:

> ERROR:Exception on /api/local/local/spec [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/grlc/grlc/src/server.py", line 67, in swagger_spec_local
>     return swagger_spec(user=None, repo=None, sha=None, content=None)
>   File "/home/grlc/grlc/src/server.py", line 83, in swagger_spec
>     swag = utils.build_swagger_spec(user, repo, sha, static.SERVER_NAME)
>   File "/usr/local/lib/python3.6/site-packages/grlc/utils.py", line 75, in build_swagger_spec
>     spec = swagger.build_spec(user, repo, sha, prov_g)
>   File "/usr/local/lib/python3.6/site-packages/grlc/swagger.py", line 135, in build_spec
>     item = process_sparql_query_text(query_text, loader, call_name, extraMetadata)
>   File "/usr/local/lib/python3.6/site-packages/grlc/swagger.py", line 184, in process_sparql_query_text
>     endpoint, auth = gquery.guess_endpoint_uri(query_text, loader)
>   File "/usr/local/lib/python3.6/site-packages/grlc/gquery.py", line 45, in guess_endpoint_uri
>     decorators = get_yaml_decorators(rq)
>   File "/usr/local/lib/python3.6/site-packages/grlc/gquery.py", line 266, in get_yaml_decorators
>     yaml_string = "\n".join([row.lstrip('#+') for row in rq.split('\n') if row.startswith('#+')])
> AttributeError: 'dict' object has no attribute 'split'

This used to work with the latest dev version a few months back.

**Comment by c-martinez** [comment]
It looks like the issue might come from how config file is being loaded:

https://github.com/CLARIAH/grlc/blob/94506d445a0992df750c358cb592089c6cf14439/src/static.py#L50

In the docker image, the config file is not being found, and therefore the `local` repo is not being found. Will look into it later this week.

**Comment by c-martinez** [comment]
Hey @tkuhn -- `dev` image in dockerhub should work now. The `latest` image should be fixed when merged to `master`. I'm assuming you were working with the `dev` image?

Closing this issue.

**Comment by tkuhn** [comment]
Yes, works now. Thanks!
