### ISSUE TITLE
SPARQL Transformer breaks with non-query json files

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/grlc#213]
sparql transformer handles json files with a specific format:

https://github.com/CLARIAH/grlc/blob/94506d445a0992df750c358cb592089c6cf14439/src/gquery.py#L262-L267

However these lines will not handle other json files. This means that other json files in the api repository will cause an error.

**Comment by pasqLisena** [comment]
Hi @c-martinez, please assign this issue to me

**Comment by c-martinez** [comment]
Closed by #216
