### ISSUE TITLE
Improving SPARQL transform

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/grlc#215]
The proposal is merge the functionality of SPARQLtransform and projections (pyql files). We would prefer for queries to always be expressed as SPARQL, in order not to loose any of the SPARQL expressiveness, but to keep the transform result representation capability -- results from queries expressed as json. The transform syntax could be included using the `transform` keyword.

The `.rq` file would look like this:
```
#+ summary: Brief description of this query
#+ endpoint_in_url: False
#+ endpoint: "http://endpoint/sparql/"
#+ transform: {
#+     "id": "?id",
#+     "class": "$rdf:type$required$var:?class",
#+     "label": "$rdfs:label$required",
#+     "o": "?o"
#+   }

prefix dcterms: <http://purl.org/dc/terms/>

SELECT ?p ?o WHERE
{
  ?_s ?p ?o
}
```

@pasqLisena -- I discussed this with @albertmeronyo and we agreed this might be the best way forward. Do you have any comments / suggestions?

**Comment by pasqLisena** [comment]
Hello @c-martinez, I agree that the next step is extracting the transforming capabilities of the module.
I received different suggestions on this topic and I will soon study the problem and produce the best solution.

**Comment by c-martinez** [comment]
Hi @pasqLisena -- great! Let us know if you have any suggestions or other recommendations for the grlc implementation.

**Comment by c-martinez** [comment]
Hey @pasqLisena,
I'm implementing the new functionality as discussed above, with some simplifications. More specifically, I was trying to project results from this query:

```SPARQL
SELECT ?p ?o WHERE
{
  ?_s ?p ?o
} LIMIT 5
```
into something like this:
```JSON
{
  "p1":"o1",
  "p2":"o2",
  "p3":"o3",
  "p4":"o4",
  "p5":"o5"
}
```
However, it looks like `SPARQLTransformer` always returns a list? It also looks like it must always have an `id` -- is that correct? What is the reasoning behind it?

**Comment by pasqLisena** [comment]
> However, it looks like SPARQLTransformer always returns a list?

Normally yes. 

> It also looks like it must always have an id -- is that correct? What is the reasoning behind it?

Yes, the id is an anchor for merging. For now, it is hardcoded, planning to make it selectable.

---
Back to your template, I am surprised that you don't want something like :

```js
[
  {"p1" : "o1"},
  {"p2" : "o2"},
  {"p3" : "o3"},
  {"p4" : "o4"},
  {"p5" : "o5"}
]
```

Anyway, for now, SPARQL Transformer is capable to output something like:

```js
[
  {"p" : "p1",
  "o" : "o1" },
  {"p" : "p2",
  "o" : "o2" },
  ...
]
```

in other words, only the attribute values are replaced, while attribute names are not touched.

**Comment by c-martinez** [comment]
Ok, that kind of makes sense. And what would be the correct syntax for such a projection? I imagine I should use something like this (given that the `id` is required at the moment):
```JS
{
  "id": "?p",
  "value": "?o"
}
```

Would give me something like:
```JS
[
  { "id" : "p1",  "value" : "o1" },
  { "id" : "p2",  "value" : "o2" },
  ...
]
```
Is that correct?

**Comment by pasqLisena** [comment]
Exactly

**Comment by pasqLisena** [comment]
Hi @c-martinez, I just released a version of ST in which you can replace that hard-coded `id` with any other property with a `$anchor` modifier. See [documentation](https://github.com/D2KLab/sparql-transformer#the-prototype)

**Comment by c-martinez** [comment]
Hi @pasqLisena. Nice! So this means I should be able to write something like this: 
```JS
{
  "key": "?p$anchor",
  "value": "?o"
}
```
and get the desired result. Correct?
