### ISSUE TITLE
not sure how to retrieve data appropriately from grlc query API

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/grlc#217]
Hi, I've setup my grlc api [1] for this query [2]. Running the results 'manually' (by clicking 'execute' and so on) all seems to work fine. But when I try to retrieve the results via Python, it appears as the output is not properly formatted, as it start with `b'`:

```
b'"id","title","geom_source","ccodes","min","max","citation"\n"https://iisg.amsterdam/resource/country/Afghanistan/1946","Afghanistan","http://nils.weidmann.ws/projects/cshapes.html","AF",1946-01-01,2016-06-30,"https://druid.datalegend.net/nlgis/cshapes/"\n
```
 I use this [3] python script. Could you please give me an example of how I'm supposed to retrieve the query via Python (pandas)? Is there a way to omit the ^^xsd:<stuff> from the result set?

Sorry noob power...

Richard

[1] http://grlc.io/api/rlzijdeman/lp-sparql-tsv-queries#/country%20level/get_lp_cshapes_query
[2] https://druid.datalegend.net/rlzijdeman/whgazetteer/queries/retieveCountriesforMountainTypes/6
[3] https://github.com/rlzijdeman/lp-sparql-tsv-queries/blob/master/retrieve-query-example.py

**Comment by rijpma** [comment]
Try decode? `resp.content.decode("utf-8")`

**Comment by rlzijdeman** [comment]
cheers, that worked. for future reference:
```
#import libraries
import pandas as pd
import requests
import io

# set info for retrieval
url = "http://grlc.io/api/rlzijdeman/lp-sparql-tsv-queries/lp-cshapes-query?endpoint=https%3A%2F%2Fapi.druid.datalegend.net%2Fdatasets%2Fnlgis%2Fcshapes%2Fservices%2Fcshapes%2Fsparql"
headers={'accept': 'text/csv'}

# retrieve and format data
resp = requests.get(url, headers = headers)
respClean = io.StringIO(resp.content.decode("utf-8"))
df = pd.read_csv(respClean, sep = ",")

# write to tsv file
df.to_csv("./cshapes-whgz.tsv", sep="\t", index = False)

# EOF
```
