### ISSUE TITLE
Debug mode?

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/grlc#221]
Apparently debug mode/logging is not being turned on, even if declared in `docker-compose.yml`

```
DEBUG=true
```

or in `config.ini`:

```
# Logging level
debug = True
```

@c-martinez could you take a look? Thanks!

**Comment by c-martinez** [comment]
@albertmeronyo -- this one you managed to fix, correct? I'll close this, but reopen if it is still an issue.
