### ISSUE TITLE
Start using stable version numbers on hub.docker.com.

### ISSUE THREAD

**Issue by barrynl** [CLARIAH/grlc#228]
Hi all, 

I am using GRLC from hub.docker.com and whenever a bug is introduced in one of the latest or dev tags, my applications breaks. It always takes me some time to realize the problem is (for once) not with me, but with the hub.docker.com image :)

it would be nice if the hub.docker.com repository of grlc used some sort of stable version numbering instead of 'latest' and 'dev' tags.

Regards, Barry

**Comment by c-martinez** [comment]
Hi @barrynl -- that is a good point. Perhaps we should set up docker hub to build a `stable` image only when we do a new release (and perhaps have a `dev` image build from the `dev` branch. -- what do you think @albertmeronyo ?

**Comment by c-martinez** [comment]
From version 1.3.2, images on hub.docker.com are tagged for each release version, e.g. `docker pull clariah/grlc:v1.3.2`
