### ISSUE TITLE
Problems with local queries on both the dev and master branch.

### ISSUE THREAD

**Issue by barrynl** [CLARIAH/grlc#229]
Hi all, 

Thanks for providing and maintaining grlc! I'm having some issues with grlc. 

I use the docker images provided via hub.docker.com, but both the latest (which is probably generated from the master branch) and the dev tag will not load my local queries. Due to issue #208 I already switched from the latest to the dev tag a while back, but now the dev tag also stopped working for local queries (not sure why). Unfortunately, I cannot switch back to the latest tag, because the patch described in #208 is not yet merged with the master branch.

As a temporary solution I cloned the grlc repo and build a docker image myself after patching the fix attached to #208 and then the local queries work correctly. But I prefer the hub.docker.com version to be working, because some colleagues of mine also use it.

Thanks in advance!

Regards, 

Barry

p.s. see also a more general issue I just created: #228

**Comment by c-martinez** [comment]
Hi @barrynl -- I guess this is no longer an issue. [Dockerhub versions](https://hub.docker.com/repository/docker/clariah/grlc/tags?page=1) are now tagged per release as you suggested, and issue #208 is closed.
