### ISSUE TITLE
queries are no longer loaded

### ISSUE THREAD

**Issue by barrynl** [CLARIAH/grlc#232]
Hi all, 

Am I the only one seeing only the green header and no queries on the following GRLC.io webpage? [http://grlc.io/api/albertmeronyo/lodapi/](http://grlc.io/api/albertmeronyo/lodapi/)

I am experiencing problems with GRLC: my local queries are no longer loading. I use GRLC in a docker container and these images no longer work. I tried to build my own docker image from the GRLC git repository, but these all behave the same. It only shows the green header as with the webpage above.

Any ideas?

Regards, Barry

**Comment by barrynl** [comment]
The problem seems to lie in this file: https://github.com/CLARIAH/grlc/blob/master/src/templates/api-docs.html#L86

It seems like the file: https://unpkg.com/react@16/umd/react.development.js is no longer accessible due to CORS policies on the unpkg.com website.

**Comment by barrynl** [comment]
There is already an issue for UNPKG on github: https://github.com/mjackson/unpkg/issues/229

**Comment by barrynl** [comment]
I've fixed this locally by removing the 'crossorigin' attribute of the 'script' tag: 

https://github.com/CLARIAH/grlc/blob/master/src/templates/api-docs.html#L86

**Comment by c-martinez** [comment]
Hi @barrynl -- thanks for spotting the issue. I am assuming what you did looks like [this](https://github.com/CLARIAH/grlc/pull/233/files) ?

Feel free to send a PR whenever you find an issue like this one :-)

**Comment by barrynl** [comment]
Yes, that's exactly what I did locally. Thanks for fixing!

**Comment by c-martinez** [comment]
Thanks you for reporting it!
