### ISSUE TITLE
Looking for subfolders named "queries"

### ISSUE THREAD

**Issue by DimitrisAlivas** [CLARIAH/grlc#24]
Not all projects have their queries in a separate repository but have the queries in a subfolder.

**Comment by albertmeronyo** [comment]
@DimitrisAlivas could you point to a repo with such structure? I'm trying to recreate the issue, thanks!

**Comment by DimitrisAlivas** [comment]
@albertmeronyo Hey Albert. Our trump repo used to have such a structure but Kathrin changed it.

In order to recreate the issue you just need a folder within a repository named "queries".
If you check https://github.com/TRUMP-project/documentation, apart from the folders named "data" etc I had a "queries" folder to store queries and that's when I encountered the issue!
Hope it helps :)

**Comment by c-martinez** [comment]
This feature seems to be in demand.

**Comment by c-martinez** [comment]
This type of request should be possible using the `subdir` [option](https://github.com/CLARIAH/grlc#from-a-github-repository) or in the worst case with a [specification yaml file](https://github.com/CLARIAH/grlc#from-a-specification-file).

Closing this issue -- if this is still needed and cannot be addressed with these options, please reopen.
