### ISSUE TITLE
Document API, functions and classes for JOSS

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/grlc#244]

**Comment by c-martinez** [comment]
- [ ] Proof read README.md
- [ ] Example queries in grlc-queries
- [ ] Merge master
- [ ] Make release
- [ ] Submit to JOSS

**Comment by c-martinez** [comment]
@albertmeronyo -- submitted. Esperemos a ver que nos dicen. No lo habia hecho antes porque no estaban aceptando papers por el lockdown.
