### ISSUE TITLE
Add https: support on grlc.io

### ISSUE THREAD

**Issue by jaw111** [CLARIAH/grlc#246]
I am trying to call grlc.io from a client application served over https: and, given the browser does not allow mixed active content, the application is not allowed to see the response.

Ideally grlc.io should be available on https://grlc.io/

**Comment by c-martinez** [comment]
Hi @jaw111 -- this is a very good point.

@albertmeronyo -- any idea about this?

**Comment by jaw111** [comment]
Given there is no movement on this, I'll assume grlc.io is not actively maintained/supported and will look for other options.

Thanks.

**Comment by rlzijdeman** [comment]
all right, thanks for letting us now @jaw111 !

**Comment by albertmeronyo** [comment]
Not that we'll have time to implement this anytime soon, but the solution seems simple https://stackoverflow.com/questions/29458548/can-you-add-https-functionality-to-a-python-flask-web-server

Thanks @jaw111 for reporting

**Comment by c-martinez** [comment]
We might need to get/buy an SSL certificate from a trusted authority.

**Comment by jaw111** [comment]
p.s. 'other options' means we'll try deploying a grlc docker image into K8s cluster with SSL offloading

**Comment by c-martinez** [comment]
Ping @jaw111 -- grlc.io now supports https. In the end we did not change any part of grlc code, just the nginx configuration on the server.
