### ISSUE TITLE
endpoint not recognised from decorator?

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/grlc#250]
Hi,

I've added the endpoint inside my query[1] using the `#+ endpoint:` decorator.
However, when I go to the grlc-api page [2], click 'try it out' and 'execute' it runs against the DBpedia endpoint, not the one I provided. If I replace the DBpedia endpoint with the proper one, the results return as expected.

[1] https://github.com/rlzijdeman/ecartico-sparql/blob/master/persons-from-period.rq
[2] http://grlc.io/api/rlzijdeman/ecartico-sparql/

**Comment by albertmeronyo** [comment]
Hi @rlzijdeman 

I think it's due to the tab in your YAML line
`#+     - dates`

Can you try again with two spaces in that line instead of a tab? So
#+  - dates

**Comment by rlzijdeman** [comment]
Graciès @albertmeronyo.  Obra començada, mig acabada.
