### ISSUE TITLE
"from" clause in json pattern is not recognised

### ISSUE THREAD

**Issue by rapw3k** [CLARIAH/grlc#251]
I am trying a very simple query: to retrieve all triples from a particular graph in our triplestore in json format.
I am trying to specify the graph using the $from clause but it is not taken into account.
my repository: https://github.com/rapw3k/cybele/
query: https://github.com/rapw3k/cybele/blob/master/allmetadata_json.json

Am I doing something wrong with this?
thanks in advance

**Comment by albertmeronyo** [comment]
Thanks for reporting this @rapw3k 
@pasqLisena do you think this might be Transformer specific, or more related to the main engine?

**Comment by pasqLisena** [comment]
Hi everyone,
in grlc we include SPARQL Transformer at version 1.7.0 (see [requirements.txt](https://github.com/CLARIAH/grlc/blob/master/requirements.txt#L20)).
The `$form` attribute has been included in 1.8.1.

@albertmeronyo is it possible to bring ST version in glrc to latest (1.8.2) ?

**Comment by rapw3k** [comment]
thank you for the information, waiting for feedback about the update.

**Comment by c-martinez** [comment]
Fixed by @pasqLisena on #252
