### ISSUE TITLE
Pagination link in headers

### ISSUE THREAD

**Issue by pasqLisena** [CLARIAH/grlc#259]
The next pagination link is not working properly.

In particular, I am looking at this query:
http://grlc.eurecom.fr/api/albertmeronyo/lodapi/#/dbpedia/get_dbpedia_test

Trying it out, I can see the **Response headers**, where the `link` attribute is:
http://grlc.eurecom.fr/api/albertmeronyo/lodapi/dbpedia_test?type=http%3A%2F%2Fdbpedia.org%2Fontology%2FBand&endpoint=http%3A%2F%2Fdbpedia.org%2Fsparql?page=2

This link, instead of bringing to page 2, re-propose page 1.

The link should be corrected to: 
http://grlc.eurecom.fr/api/albertmeronyo/lodapi/dbpedia_test?type=http%3A%2F%2Fdbpedia.org%2Fontology%2FBand&endpoint=http%3A%2F%2Fdbpedia.org%2Fsparql&page=2

Briefly, we should replace the second `?` (that is correctly ignored) with a `&`.

Some checks and modifications should be done in 
https://github.com/CLARIAH/grlc/blob/0527f77c480f878a2415b8ebc1d2eafca20f6235/src/pagination.py#L22-L27

N.B. I am linking example to grlc.eurecom.fr because grlc.io is still not working.

**Comment by c-martinez** [comment]
Hi @pasqLisena,

You are probably right that it is not the best way to build the url. Probably we should use something like [urllib.parse.urlencode](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode). Although for me the `link` attribute seems to be well formed:

> link: <http://grlc.eurecom.fr/api/albertmeronyo/lodapi/dbpedia_test?page=11&type=http%3A%2F%2Fdbpedia.org%2Fontology%2FBand&endpoint=http%3A%2F%2Fdbpedia.org%2Fsparql>; rel=next, <http://grlc.eurecom.fr/api/albertmeronyo/lodapi/dbpedia_test?page=9&type=http%3A%2F%2Fdbpedia.org%2Fontology%2FBand&endpoint=http%3A%2F%2Fdbpedia.org%2Fsparql>; rel=prev, <http://grlc.eurecom.fr/api/albertmeronyo/lodapi/dbpedia_test?page=1&type=http%3A%2F%2Fdbpedia.org%2Fontology%2FBand&endpoint=http%3A%2F%2Fdbpedia.org%2Fsparql>; rel=first, <http://grlc.eurecom.fr/api/albertmeronyo/lodapi/dbpedia_test?page=20.0&type=http%3A%2F%2Fdbpedia.org%2Fontology%2FBand&endpoint=http%3A%2F%2Fdbpedia.org%2Fsparql>; rel=last 

We will be updating grlc.io to a new release soon.

**Comment by pasqLisena** [comment]
> Although for me the link attribute seems to be well formed

I am looking at the preview of the headers in the Swagger UI. At least there, the issue is more visible.
