### ISSUE TITLE
Collision between 2 routes

### ISSUE THREAD

**Issue by pasqLisena** [CLARIAH/grlc#264]
Hello,
the software is not able to distinguish between:
- `@app.route('/api/<user>/<repo>/<subdir>', strict_slashes=False)  # backward compatibility route` (line [157](https://github.com/CLARIAH/grlc/commit/f7f4af5a887235772f95f640b8434c3313e5610c#diff-94ab7c76892f0032ee9ad040e3e8f207R157)
- `@app.route('/api/<user>/<repo>/<query_name>', methods=['GET', 'POST'])  # backward compatibility route` (line [195](https://github.com/CLARIAH/grlc/commit/f7f4af5a887235772f95f640b8434c3313e5610c#diff-94ab7c76892f0032ee9ad040e3e8f207R195)

The result is that the first one is always picked

(also reported [here](https://github.com/CLARIAH/grlc/commit/f7f4af5a887235772f95f640b8434c3313e5610c#commitcomment-39093522))

**Comment by c-martinez** [comment]
Hi @pasqLisena you are absolutely right. This is an issue with the old routes -- we are not changing the API for these old routes, but I think it has been solved for the new routes (the ones starting with `/api-git`. In a future release (probably `1.4.0` these routes will be removed.

**Comment by pasqLisena** [comment]
Ah, but this means that all applications that relied on `/api` path must be updated?
(Basically, the new update will be not backwards compatible)

**Comment by c-martinez** [comment]
Yes, they will have to be updated. And yes, they will not be backward compatible, which according to [semver](https://semver.org/) should be a MAJOR version change (when you make incompatible API changes). So it should be for release `2.0.0`.
