### ISSUE TITLE
organize hang-out

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/grlc#270]
That is good to hear @jblom. Yes it would be nice to organise a hang-out and see what you guys are up to :-) -- just let us know when you have some time.

_Originally posted by @c-martinez in https://github.com/CLARIAH/grlc/pull/224#issuecomment-643158784_

**Comment by jblom** [comment]
@rlzijdeman hey this is turning into a nice group for a hang-out with a neat topic :-)

So definitely nice to have a session somewhere in the weeks to come. @mwigham and @wmelder should join too.

(Will send you my contact details in mail, got your call from our service desk)

**Comment by c-martinez** [comment]
Hey @rlzijdeman -- we could organise this grlc hang-out as part of the [NL-RSE meetups](https://nl-rse.org/pages/meetups.html), would that be an idea?

**Comment by rlzijdeman** [comment]
@c-martinez that would be great... I actually lost your mail address and asked eScience for it, but have not heard back. Could you please drop me a line at richard.zijdeman AT whereIwork.nl?

**Comment by c-martinez** [comment]
This is being planned for the NL-RSE meetup on the 13 November -- closing this issue.
