### ISSUE TITLE
Support other branches than master in api-git

### ISSUE THREAD

**Issue by vemonet** [CLARIAH/grlc#296]
GitHub just changed the default branch from `master` to `main` (in relation the the Black Lives Matter movement)

When publishing my API using api-git I realized grlc would only try to resolve the `master` branch, even if there was only 1 branch (`main` in my case)

Ideally grlc should take the default branch defined on GitHub, it would be more sustainable as more and more repo will use `main` as default branch

Thanks a lot!

**Comment by c-martinez** [comment]
Hi @vemonet -- Thanks for reporting this! You are absolutely right, this is an excellent suggestion. Could you point me to the repo you are using to test, so I can check what is going on?

**Comment by vemonet** [comment]
Here is the repository I am using: https://github.com/MaastrichtU-IDS/food-claims-kg

Unfortunately I created a `master` branch, made it default and it is now working flawlessly, so I am not sure if you will be able to test on it. I still have the `main` branch though

**Comment by c-martinez** [comment]
Thanks @vemonet -- I guess the easiest is to create a new repo with just a `main` branch and test with that.

**Comment by vemonet** [comment]
@c-martinez I am seeing you are using PyGithub instead of the API

Just for your information you also get the default branch using the GraphQL API with `defaultBranchRef` and using `HEAD` in the search expression

Example:

```graphql
query {
	repository(name: MYREPO, owner: MYOWNER){
    url
    shortDescriptionHTML
    name
    description
    defaultBranchRef {
      name
    }
    object(expression: "HEAD:") {
      ... on Blob {
        text
      }
      ... on Tree{
        entries {
        name
        path
        object {
          ... on Blob {
            text
          }
[close all brackets :) ]
```

**Comment by c-martinez** [comment]
Thanks @vemonet :-)
