### ISSUE TITLE
Can't control the format in which grlc resturns results by adding the extension to the URI;

### ISSUE THREAD

**Issue by ecow** [CLARIAH/grlc#304]
As written in the the wiki, it should be possible to force an output format just adding a proper extension to the API Uri. But in my host, it seams  not working (using docker clariah/grlc:v1.3.5):

`curl -X GET "http://localhost:29602/api-local/myquery" -H "accept: text/csv"`  works as a charm.

`curl -X GET "http://localhost:29602/api-local/myquery.ttl"` returns 404 ("Couldn't find a SPARQL, RDF dump, or TPF query with the requested name")

Thank you for this great tool!

**Comment by c-martinez** [comment]
Hi @ecow,

It is possible to force the output format by using the extension. For example if you use one of the test queries from `http://grlc.io/api-git/CLARIAH/grlc-queries/` you can do:

Output format CSV via content negotiation:
```bash
curl -X GET "http://grlc.io/api-git/CLARIAH/grlc-queries/summary" -H "accept: text/csv"
```

Output format turtle via content negotiation:
```bash
curl -X GET "http://grlc.io/api-git/CLARIAH/grlc-queries/summary" -H "accept: text/turtle"
```

Output format csv via extension:
```bash
curl -X GET "http://grlc.io/api-git/CLARIAH/grlc-queries/summary.csv"
```

Output format turtle via extension:
```bash
curl -X GET "http://grlc.io/api-git/CLARIAH/grlc-queries/summary.ttl"
```

*BUT* -- this feature only works with the `/api-git/`. For `/api-local` (and `/api-url`) only content negotiation method is implemented. So you would need to do: 

```bash
curl -X GET "http://localhost:29602/api-local/myquery" -H "accept: text/turtle"
```

Actually, @albertmeronyo and I debated some time ago whether content negotiation should be done just by extension, just by content negotiation, or both. We did not reach any conclusion. Perhaps this is a good indicator to restart that discussion.

**Comment by ecow** [comment]
To use the file extension to force a content type using an extension in the resource URI is a common  practice in linked data and in the web architecture specification. See dbpedia for example.
To properly manage this case,  the HTTP protocol defined the week validation for ETAG (also called semantic eTag) in order to allow cache optimization. This means that, for instance, the resource "http://grlc.io/api-git/CLARIAH/grlc-queries/summary.ttl" and the resource "http://grlc.io/api-git/CLARIAH/grlc-queries/summary" (extracted with -H "accept: text/turtle") sholud expose th same weak eTag (i.g. W/xxxxxxxx). If needed, this  should not too complex to implement in grlc.

In my opinion, the best sholud be to  support content negotiation on URI without extension and force a content type if extension is provided. But this behaviour should be consistent both on api-git and api-local

**Comment by ecow** [comment]
P.S. I'm a quite an old good experienced programmer (php, bash, awk, perl, C) but as today  I do not know phyton, if some one can  suggest me a good learnin resource and some hints I can try to hack the code.

**Comment by albertmeronyo** [comment]
Thanks for reporting this @ecow 
We originally supported both types of content negotiation, and both are useful. I agree the extension trick is quite common in Linked Data. I think this is a bug we introduced while updating to the new grlc API as route patterns are becoming increasingly complex (this would be a separate discussion though).

I'll be happy to upgrade this to a bug and ask for PRs. @c-martinez what do you think?

**Comment by c-martinez** [comment]
My personal preference would be to just have one way of doing the content negotiation (via the HTTP header), but if the extension trick is common in linked data land, then I'm happy to stick to that convention. then we should indeed support this on the `/api-local` and `/api-url` routes.

**Comment by ecow** [comment]
Hi, is there a road map for a release correcting this bug?

**Comment by c-martinez** [comment]
Hi @ecow -- we should be making a new release in the next week or so. We will [tweet](https://twitter.com/grlcldapi) when the new release is published :-)

**Comment by ecow** [comment]
Great news. Thank you for this great product.

**Comment by ecow** [comment]
Great!! Now it works with 1.3.6
