### ISSUE TITLE
Document support for Linked Data Fragments

### ISSUE THREAD

**Issue by alexdma** [CLARIAH/grlc#311]
The [feature list](https://github.com/CLARIAH/grlc/wiki/Features) mentions compatibility of GRLC with LD fragments.

Whether this means that one can supply an LD fragment server as an `endpoint` parameter, then a specification as to what the query should look like, in order to be parsable by GRLC, would make things clearer. Or even if I have completely mistaken the notion of LDF compatibility for GRLC, it would best be documented.

It would be useful if a small tutorial could be provided in the documentation, with examples running on http://fragments.dbpedia.org or others.

Thanks!

**Comment by c-martinez** [comment]
Hi @alexdma, Thank you for your comment. I suppose this is related to https://github.com/openjournals/joss-reviews/issues/2731, correct?

Indeed it would be good to have a well documented example of how to use this feature. Perhaps as part of the [quick tutorial](https://github.com/CLARIAH/grlc/wiki/Quick-tutorial).

@albertmeronyo -- what do you think? Do you have an old example we could use to document this feature?

**Comment by alexdma** [comment]
Hi @c-martinez - that is correct, I will be sure to mention the JOSS ticket in any related issues I might open.

**Comment by alexdma** [comment]
I agree that it does. Thank you and nice work adding LDF documentation!

**Comment by arfon** [comment]
> I agree that it does. Thank you and nice work adding LDF documentation!

:+1: thanks @alexdma! When you have a moment, please update the review checklist in https://github.com/openjournals/joss-reviews/issues/2731 based on these changes.

**Comment by alexdma** [comment]
Closing in agreement with editor in chief
