### ISSUE TITLE
Internal Server with transform query decoration 

### ISSUE THREAD

**Issue by ecow** [CLARIAH/grlc#313]
Is the transform query decorator broken?

It returns 500 Internal Server Error both in my local installation (docker grlc:latest connected with a blazegraph sparql endpoint) and in the the official example (  http://grlc.io/api-git/CLARIAH/grlc-queries/#/default/get_transform )

**Comment by c-martinez** [comment]
Hi @ecow -- yes that definitely looks like a bug. Thanks for reporting this, I will look into it.

**Comment by c-martinez** [comment]
It looks like transformations work, BUT...

Transformer always works with json, so it breaks when the content-type is not json. Granted, it should break in a more graceful way.

If you set the response content type to `application/json` it should work fine:

![image](https://user-images.githubusercontent.com/7782231/106859760-c7b33b00-66c3-11eb-9394-3a03c8dd8a38.png)

Does this work for you @ecow?

I'll leave his issue open, until more graceful handling of json content type is fixed.

**Comment by ecow** [comment]
Hi, @c-martinez .
even, if using header "Accept: application/json' , my test  fails with the simple decoration:

```
#+ transform: {
#+     "label": "?label"
#+   }
```

Instead the decoration

```
#+ transform: {
#+     "label": "?label",
#+     "$anchor": "label"
#+   }
```
works well, producing something like:

```
[
  {
    "label": {
      "language": "it",
      "value": "string1"
    }
  },
  {
    "label": {
      "language": "it",
      "value": "string2"
    }
  }
]
```

 Is "$anchor" mandatory?

I would like to produce just a simple structure like:

[ 
   "string1", 
   "string2"
]

Who to do it ? (if possible)?

**Comment by c-martinez** [comment]
Yes, I think the `$anchor` is mandatory. 

I'm not an expert on transformer syntax, but maybe check [their documentation](https://github.com/D2KLab/sparql-transformer). Otherwise, perhaps @pasqLisena might be able to shed some light.

**Comment by pasqLisena** [comment]
Hi, yes the software requires an `$anchor` or an `id` field.
You can eventually mark it in this way:

```
transform: {
    "label": "?label$anchor"
}
```

**Comment by c-martinez** [comment]
Hi @ecow -- I just wanted to check with you if @pasqLisena's suggestion helped you solve your problem and if I can close this issue?

**Comment by ecow** [comment]
Yes, you can close these issue but docs should be updated. Thank you.
