### ISSUE TITLE
Parameter isn't recognized in a filter + concat

### ISSUE THREAD

**Issue by yannnic** [CLARIAH/grlc#322]
GRLC does not recognize the parameter in this [query](https://github.com/yannnic/grlc-test2/blob/master/byidref.rq).
The parameter is inside a concat inside a filter :
`FILTER(?idrefuri = URI(CONCAT('http://www.idref.fr/', ?_idrefid, '/id')))`

Here is a working example without the GRLC param :
```
SELECT ?oeuvre ?titre ?role  
WHERE 
 {  
      ?oeuvre dcterms:title ?titre ; vivo:relatedBy [vivo:relates ?idrefuri ; v:hasRole ?role] .
      FILTER(?idrefuri = URI(CONCAT('http://www.idref.fr/', '184032997', '/id')))
 }
LIMIT 10
```

Endpoint : https://scienceplus.abes.fr/sparql

Cheers

**Comment by c-martinez** [comment]
Hi @yannnic,

Yes, unfortunately, `?_idrefid` is not considered to be a variable when it is inside a `CONCAT` (grlc uses rdflib under the hood, and rdflib does not recognise it as a variable). We had come across this issue before (see #230). 

As a workaround you could do something like this:

```SPARQL
SELECT ?oeuvre ?titre ?role  
WHERE 
 {  
      OPTIONAL { ?s ?p ?_idrefid }
      ?oeuvre dcterms:title ?titre ; vivo:relatedBy [vivo:relates ?idrefuri ; v:hasRole ?role] .
      FILTER(?idrefuri = URI(CONCAT('http://www.idref.fr/', ?_idrefid, '/id')))
 }
 LIMIT 10
```

The `?_idrefid` **is** considered a variable inside the `OPTIONAL` clause, which allows for the variable replacement to happen.

Would this work for you?

Cheers

**Comment by yannnic** [comment]
Hi @c-martinez,
the proposed workaround works perfectly. Astute trick :)
Thank you so much.
I love grlc. It is very useful and elegant.

Good night

Yann
