### ISSUE TITLE
[Software paper] Describe the state of the field

### ISSUE THREAD

**Issue by alexdma** [CLARIAH/grlc#325]
Re openjournals/joss-reviews#2731

Paragraph 2 of the JOSS paper at https://github.com/openjournals/joss-papers/blob/joss.02731/joss.02731/10.21105.joss.02731.pdf

describes the motivation of Grlc properly. It would best be complemented by a brief outline of the approaches taken regarding the field at hand (say, programmatic access to the Web of Linked Data without having to know SPARQL).

Since both BASIL and LD Fragments are incorporated into this work, it might be useful to refer to them and briefly build upon their state of the art.

**Comment by c-martinez** [comment]
Thanks for your suggestions @alexdma 

@albertmeronyo -- would [this](https://github.com/basilapi/basil/wiki/SPARQL-variable-name-convention-for-WEB-API-parameters-mapping) be a good reference for BASIL? And [this one](https://linkeddatafragments.org/publications/jws2016.pdf) for LD fragments?

**Comment by albertmeronyo** [comment]
Both links are perfect @c-martinez , thanks!

**Comment by alexdma** [comment]
Thanks! Where can I view the updated paper?

**Comment by c-martinez** [comment]
No problem -- I just generated a [fresh version](https://github.com/openjournals/joss-papers/blob/joss.02731/joss.02731/10.21105.joss.02731.pdf) in the [joss issue](https://github.com/openjournals/joss-reviews/issues/2731)
