### ISSUE TITLE
[Software paper] Minor corrections

### ISSUE THREAD

**Issue by alexdma** [CLARIAH/grlc#326]
Re openjournals/joss-reviews#2731

https://github.com/openjournals/joss-papers/blob/joss.02731/joss.02731/10.21105.joss.02731.pdf

can you please check the following

- First paragraph, end: "requires certain level of expertise" -> "a certain level" (or rephrase e.g. "some degree of expertise", "some expertise")
- Second pagaraph: "face the challenge _of_ having to learn SPARQL"

**Comment by c-martinez** [comment]
Hi @alexdma -- we've implemented these minor corrections. Thank you for suggesting them!
