### ISSUE TITLE
object vs list of objects in the API output

### ISSUE THREAD

**Issue by rapw3k** [CLARIAH/grlc#328]
Hi, 
In our project Cybele, we are trying to integrate and reuse the API in other services; however, there is one issue we are not sure how to handle.

In the endpoint: http://grlc.io/api-git/rapw3k/cybele/#/json/get_allDatasets 
we have among others this specification.
```
"measure": {
        "id": "$qb:component/qb:measure",
        "label": "$rdfs:label",
        "range": "$rdfs:range",
        "UoM": "$sdmx-attribute:unitMeasure",
        "description": "$rdfs:comment"
      }
```
The output of this endpoint returns a list of objects when there are more than one resource associated, but when is only one resource associated it is returned as a simple object. Is there a way we specify that the output should always be a list of object, even if its only one result, or any work around this?
Example output with more than one "measure"
```
"measure": [
        {
          "UoM": "http://qudt.org/vocab/unit/DEG_C",
          "description": "The average air temperature in Degree Celsius",
          "id": "https://w3id.org/cybele/measure/averageAirTemperature",
          "label": "Average air temperature",
          "range": "http://www.w3.org/2001/XMLSchema#double"
        },
        {
          "UoM": "http://qudt.org/vocab/unit/M-PER-SEC",
          "description": "The average wind speed in meter per second",
          "id": "https://w3id.org/cybele/measure/averageWindSpeed",
          "label": "Wind speed",
          "range": "http://www.w3.org/2001/XMLSchema#double"
        }
      ]
```
Example output with only one "measure"
```
"measure": {
        "description": "Number of food recall incidents per day",
        "id": "https://w3id.org/cybele/measure/incidencesNumber",
        "label": "DOC_COUNT",
        "range": "http://www.w3.org/2001/XMLSchema#int"
      }
```

**Comment by c-martinez** [comment]
Hi @rapw3k -- very good question, I'm not 100% sure how to achieve this. I'm going to pass this question to @pasqLisena who is the real expert in Transformer syntax and capabilities.

**Comment by pasqLisena** [comment]
Hi @rapw3k , it is not implemented now, but it is a good feature to have!
I opened a proper issue in the SPARQL transformer repository

**Comment by rapw3k** [comment]
thank you @c-martinez , @pasqLisena, looking forward for this update!

**Comment by c-martinez** [comment]
I will close this issue and we can track progress on the [SPARQL Transformer
 issue](https://github.com/D2KLab/sparql-transformer/issues/20).

**Comment by pasqLisena** [comment]
Hi, I implemented the feature. Now your query can become:
```json
"measure": {
        "id": "$qb:component/qb:measure$list",
        "label": "$rdfs:label",
        "range": "$rdfs:range",
        "UoM": "$sdmx-attribute:unitMeasure",
        "description": "$rdfs:comment"
      }
```
In short, by putting `$list` on a property (or on the id/anchor, for targeting the whole object), the output is forced to be a list.

@c-martinez would you mind updating the SPARQLTransformer version to latest ([2.1.1](https://pypi.org/project/SPARQLTransformer/2.1.1/))?

**Comment by c-martinez** [comment]
Hi @pasqLisena -- I've updated SPARQLTransformer version in the `dev` version. Should be updated in the `master` branch during the next release (will discuss with @albertmeronyo when that will be, but probably soon).

**Comment by rapw3k** [comment]
hi @c-martinez ,thats really cool, thanks!
tested it and works fine.
do you announce when you deploy a new release?

**Comment by c-martinez** [comment]
hi @rapw3k, great, glad it works.
We usually [tweet](https://twitter.com/grlcldapi) whenever there is a new release. Next one should be out in the next couple of weeks.
