### ISSUE TITLE
Use SPARQLWrapper ?

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/grlc#33]
Would it perhaps be an idea to use [SPARQLWrapper](https://github.com/RDFLib/sparqlwrapper) ? It already has support for handling different formats (e.g. JSON, XML, TURTLE, etc.)

**Comment by albertmeronyo** [comment]
Thanks for the issue, @c-martinez !
Our first implementation used SPARQLWrapper, but we found it limited wrt controlling content negotiation (e.g. text/csv is often implemented in endpoints but unsupported in SPARQLWrapper).
We're currently using (requests)[http://docs.python-requests.org/en/master/] to implement all HTTP interaction.
Thanks again!

**Comment by c-martinez** [comment]
Would it be easier to add the csv support to SPARQLWrapper, instead of doing it on your own? Would it make grlc easier to maintain?

(I am just curious -- please ignore me if it is not relevant)

**Comment by c-martinez** [comment]
Sent a [PR](https://github.com/RDFLib/sparqlwrapper/pull/98) to SPARQLWrapper to support `text/csv` format
