### ISSUE TITLE
Swagger-ui does not render correctly if license is not present

### ISSUE THREAD

**Issue by jaw111** [CLARIAH/grlc#330]
When generating an API from a yaml specification file accessible on the web, the swagger-ui does not generate correctly if the license is not present.

Instead it just shows **No API definition provided.**

As the license is not required in OAS 2.0, it can be omitted when there is no license provided in the yaml specification file.

**Comment by albertmeronyo** [comment]
Thanks for this @jaw111 
@c-martinez I think this means we're treating the license as mandatory; probably a default value would work just fine?

**Comment by c-martinez** [comment]
Thanks @jaw111, @albertmeronyo. Technically, it is relatively easy to treat license as optional (done in #334).

However, this raises a more philosophical issue: it grlc or a 3rd party user legally allowed to make use of queries where it is not clear how are they licensed?

I am not an expert, but I would say that it would be nice to encourage SPARQL query developers to license their queries, so others are explicitly allowed use them. At the very least, the swagger-ui should display a message such as: "Warning queries behind this API do not have a license".

Opinions?

**Comment by jaw111** [comment]
I am running a deployment of grlc in a private environment. The license is irrelevant in this setting.

I can understand it might be nice to add licenses for work released into the public domain, but that is of no concern for my usage.

Cheers
John

**Comment by c-martinez** [comment]
Closing issue and following on in #340
