### ISSUE TITLE
Upgrade grlc to use rdflib 5.0.0

### ISSUE THREAD

**Issue by jaw111** [CLARIAH/grlc#341]
We have a query in an API specification that is not parsed correctly using rdflib 4.2.2 (the `translateQuery` function fails).

Using that function locally in rdflib 5.0.0 works OK.

Suggest to update the dependency in grlc to also use rdflib 5.0.0 if that offers better support for parsing and translating queries.

See also: https://rdflib.readthedocs.io/en/stable/upgrade4to5.html

**Comment by c-martinez** [comment]
Thanks for the suggestion @jaw111 -- there is a PR for this awaiting to be merged in dev and will be in production for the next release.
