### ISSUE TITLE
xsd:date not working?

### ISSUE THREAD

**Issue by sennierer** [CLARIAH/grlc#348]
Hi,

we are trying to get that query working: https://grlc.acdh-dev.oeaw.ac.at/api/InTaVia/grlc_sparql#/default/get_person_test_dates

But whatever we do grlc does not recognize the _xsd_date in the end of the variable and thinks it is a string. Do we need to activate that functionality somewhere? Or is there something missing in the query?

Thanks!

Btw.: grlc is really great work!

**Comment by sennierer** [comment]
Ok, seems like the issue was related to #322 and similar. Adding an OPTIONAL clause with the parameter inside fixed the issur. Closing this.

**Comment by c-martinez** [comment]
Hi @sennierer -- glad to hear you managed to fix your issue :-)
