### ISSUE TITLE
calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by ecow** [CLARIAH/grlc#349]
I got this warning, I suppose some libraries need to be updated (docker version):

`/usr/local/lib/python3.6/site-packages/grlc/gquery.py:277: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.`

**Comment by c-martinez** [comment]
Thanks @ecow probably the easiest is to use `yaml.safe_load`
