### ISSUE TITLE
CORS and security errors

### ISSUE THREAD

**Issue by tkuhn** [CLARIAH/grlc#364]
Has some configuration of the https://grlc.io server changed lately? I am getting this error since today when trying to access it from JavaScript:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://grlc.io/api/peta-pico/fpsi-queries/spec. (Reason: CORS request did not succeed)

This used to work, and it seems it's still working with http://grlc.io (http instead of https). So, I have the feeling that something has changed on the server side.

This is probably related: Accessing the API URLs like https://grlc.io/api-git/peta-pico/fpsi-queries/ gives me a security error.

**Comment by c-martinez** [comment]
Security error should be gone now -- server certificate had expired. I've renewed it now.
