### ISSUE TITLE
FAIRness badge

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/grlc#383]
Score:
[![FAIR checklist badge](https://ardc-fair-checklist.github.io/ssg/badge.svg)](https://ardc-fair-checklist.github.io/ssg/software/v0.1?f=312322&a=3323&i=20&r=424212)

**Comment by c-martinez** [comment]
Service has moved, and is now available here: [![FAIR checklist badge](https://ardc-fair-checklist.github.io/ssg/badge.svg)](https://ardc-fair-checklist.github.io/ssg/v0.2?f=3&a=132113&i=32121&r=123)

**Comment by jspaaks** [comment]
Repo name was updated deprecating the "ssg" part

```text
[![FAIR checklist badge](https://ardc-fair-checklist.github.io/badge.svg)](https://ardc-fair-checklist.github.io/v0.2?f=31&a=32113&i=32121&r=123)
```

[![FAIR checklist badge](https://ardc-fair-checklist.github.io/badge.svg)](https://ardc-fair-checklist.github.io/v0.2?f=31&a=32113&i=32121&r=123)
