### ISSUE TITLE
Returning JSON-LD 

### ISSUE THREAD

**Issue by rapw3k** [CLARIAH/grlc#385]
hi @c-martinez 
I have been trying to produce JSON-LD responses.
-- first question
I tried the examples, e.g., 
https://dev.grlc.io/api-git/Stargate-h2020/gaiasense-aim-ogc/#/testbed/get_city_region_list_ld 

However it throws an error.  Do I need to change something in the query?

-- second question. 
Is it possible to generate JSON-LD from sparql queries (.rq files) ? We have the transform decorator but we would need to add the @context, and @graph outside the response generated

**Comment by c-martinez** [comment]
Hi @rapw3k ,

From what I can see, your query is being converted into something like this:

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?id (sql:BEST_LANGMATCH(?v2, "en;q=1, it;q=0.7 *;q=0.1", "en") AS ?v2) ?v3 ?v4r ?v41
        WHERE {
          ?id a dbo:City.
          ?id dbo:country dbr:Italy.
          ?id rdfs:label ?v2.
          ?id foaf:depiction ?v3.
          ?id dbo:region ?v4r.
          OPTIONAL { ?v4r rdfs:label ?v41.
          FILTER(lang(?v41) = 'it') }
        }
         LIMIT 50 OFFSET 0
```
But then it seems to be failing when it transforms the result and sends it back (from what I can see)

to answer your second question, yes it is possible to create json from sparql queries -- see https://github.com/CLARIAH/grlc-queries/blob/master/transform.rq

**Comment by rapw3k** [comment]
thanks @c-martinez but my point  is to return  JSON-LD, not JSON. See difference here: https://github.com/D2KLab/sparql-transformer#query-in-json . 
THe first question is about  returning JSON-LD from JSON query (which can be done in theory), but the example does not work for me. 
The second questions is about returning JSON-LD from SPARQL query. Basically the resultoing JSON now shoule be wrapped in somehting like
{
  "@context": "http://schema.org/",
  "@graph": [{
<result in JSON>
]}
}

**Comment by c-martinez** [comment]
Good point @rapw3k , I kind of missed that you wanted JSON-LD, not JSON. I am not sure if it is possible to add the extra wrapping to the result. 

@pasqLisena, would you know if this is possible?

**Comment by rapw3k** [comment]
thanks @c-martinez.  

Actually as grlc is using SPARQL Transformer, which supports constructing JSON and JSON-LD outputs,  in theory should be possible. see the [example query in SPARQL Transformer](https://github.com/D2KLab/py-sparql-transformer/blob/master/examples/json_queries/city.region.list.ld.json) But I cannot make it work....

**Comment by c-martinez** [comment]
I tried the following:

```SPARQL
#+ summary: Testing if we can create json-ld
#+ endpoint: http://dbpedia.org/sparql
#+ transform: {
#+  "@context": "http://schema.org/",
#+  "@graph": [{
#+     "id": "?id",
#+     "v2": "?v2",
#+     "v3": "?v3",
#+     "v4": "?v4r",
#+     "v5": "?v41"
#+   }]
#+ }

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?id (sql:BEST_LANGMATCH(?v2, "en;q=1, it;q=0.7 *;q=0.1", "en") AS ?v2) ?v3 ?v4r ?v41
        WHERE {
          ?id a dbo:City.
          ?id dbo:country dbr:Italy.
          ?id rdfs:label ?v2.
          ?id foaf:depiction ?v3.
          ?id dbo:region ?v4r.
          OPTIONAL { ?v4r rdfs:label ?v41.
          FILTER(lang(?v41) = 'it') }
        }
         LIMIT 50 OFFSET 0
```

but that creates multiple "@context": "http://schema.org/",  "@graph": elements.

If there is no way to do this with transform syntax, I think your best bet is to do this outside grlc by wrapping the response you get from grlc with the additional JSON-LD syntax.

Does that make sense?

**Comment by pasqLisena** [comment]
I am reading this now. The query of @rapw3k (first message) looks correct, it is weird that it is not working (it appears to work on SPARQL Transformer).

@c-martinez I would like to debug. Do you have some command to run grlc in dev mode? Or I need to install the package every time there are changes?

**Comment by rapw3k** [comment]
thanks to both of you
@c-martinez wrapping the output of grlc in another mini service on top can be possible. But we would need to add yet another virtual layer, which will expose all the endpoints we are exposing in grlc, and for each of them, it will call the grlc counterpart and wrap the result and return JSON-LD. So, we loose a lot the grlc benefit, and maintainting this will be difficult....  So, lets see all possibilities we have now with grlc as it uses SPARQL Transformer, and then we can check.

@pasqLisena we also tried debuging, but now we cannot even install grlc, so we cannot debug. See issue: https://github.com/CLARIAH/grlc/issues/386. @c-martinez can you check grlc builds?

thanks

**Comment by c-martinez** [comment]
Hey both

@rapw3k, yes, I can see that wrapping another service on top is not idea. Hopefully we can do this with Transformer.

@pasqLisena, you can enable grlc in debug mode by setting this in your config.ini (see https://github.com/CLARIAH/grlc/blob/master/config.default.ini for an example).

@rapw3k, build issues should be fixed with #389

**Comment by nichtich** [comment]
The current response transformation feature is not suitable to generate JSON-LD because it can only transform flat response rows. The true benefit of JSON-LD is to encode an RDF graph. A better example would be a SPARQL CONSTRUCT query returning a list of RDF triples. To support transforming these into JSON-LD, GRLC requires [a JSON-LD processor such as pyld](https://github.com/digitalbazaar/pyld) and execute JSON-LD framing. In the end it's just a few lines of code but not doable without a JSON-LD processor.

**Comment by c-martinez** [comment]
Hi @nichtich . Thanks for pointing us to pyld. I am not sure if this is something that would be more suitable to for [py-sparql-transformer](https://github.com/D2KLab/py-sparql-transformer/) to support (rather than grlc), but maybe @pasqLisena might have more of an idea there?

grlc returning JSON-LD is definitely something that we would like to support.

**Comment by nichtich** [comment]
py-sparql-transformer is something different. Transforming lists of triples to JSON-LD given a JSON-LD context document is a standard functionality of JSON-LD processors such as pyld. I'd welcome support in grlc because otherwise it is of little use to us (we would write our own SPARQL-API wrapper instead).

**Comment by c-martinez** [comment]
What I meant to say is that grlc already uses py-sparql-transformer, so if we were to add JSON-LD functionality to it, it would be automatically supported by grlc.

In any case, returning JSON-LD is something that we plan to add. I'm not sure on what time frame, but it is in the list of enhancements.

**Comment by c-martinez** [comment]
Just checking, I think I might be able to solve the JSON-LD issue. Does the following output looks reasonable? (sorry, I'm not an expert with JSON-LD.

```json-ld
{
  "@context": "http://schema.org/",
  "@graph": [
    {
      "@id": "http://dbpedia.org/resource/Caiazzo",
      "@type": "City",
      "image": "http://commons.wikimedia.org/wiki/Special:FilePath/Caiazzo_panorama.jpg",
      "label": {
        "@language": "it",
        "@value": "Campania"
      },
      "name": {
        "@language": "en",
        "@value": "Caiazzo"
      },
      "region": "http://dbpedia.org/resource/Campania"
    },
    {
      "@id": "http://dbpedia.org/resource/Caivano",
      "@type": "City",
      "image": "http://commons.wikimedia.org/wiki/Special:FilePath/Caivano.jpg",
      "label": {
        "@language": "it",
        "@value": "Campania"
      },
      "name": {
        "@language": "en",
        "@value": "Caivano"
      },
      "region": "http://dbpedia.org/resource/Campania"
    },
   ...
}
```

**Comment by c-martinez** [comment]
I got JSON-LD generation working on [a branch](https://github.com/c-martinez/grlc/tree/json-ld). If someone can confirm this looks correct, I will merge this into `dev` (and will make its way to `master` in the next release)

**Comment by c-martinez** [comment]
Hi @rapw3k , @nichtich, PR #429 solves this issue. If you could test this works for you, it would be fantastic. Otherwise, I will just merge this as it is :-)

**Comment by c-martinez** [comment]
PR #429 merged, closing issue
