### ISSUE TITLE
Help me to install most fresh version

### ISSUE THREAD

**Issue by ecow** [CLARIAH/grlc#392]
Hi,
I'm trying to install grlc using the pip method as reported in README.

It seems that Pip installs the  1.3.6 version that was updated about two years ago.
How can I install the most updated safe version? 

Sorry for this stupid question, but I'm a newbie to python

**Comment by ecow** [comment]
P.S. I'm using docker  python:3.8.16

**Comment by c-martinez** [comment]
Hi @ecow -- version 1.3.7 is the most up-to-date version available on [PyPI](https://pypi.org/project/grlc/), unfortunately, at the time of release, it was only tested with Python 3.7, so it is restricted to `Requires: Python >=3.7, <=3.8` (this means that with Python 3.8.16, you get 1.3.6).

There is already a PR which is tested up till Python version 3.9 (see #389, just merged into `dev`). Unfortunately this is not yet released. Hopefully we will make a new release soon.

In the mean time, you can install the latest version from the `dev` branch like this:
```bash
git clone --branch dev git@github.com:clariah/grlc.git 
cd grlc/
pip install .
```

I hope this helps!

**Comment by c-martinez** [comment]
This should also work:

```bash
pip install git+https://github.com/CLARIAH/grlc.git@dev#egg=grlc
```

**Comment by ecow** [comment]
Thank you!! It works like a charm
