### ISSUE TITLE
Not able to access the instance 

### ISSUE THREAD

**Issue by trevorlazarus** [CLARIAH/grlc#47]
Hi, I think I'm missing something during the setup and am not able to access the grlc instance, I've tried the Docker way as well as the Python setup.

**Comment by albertmeronyo** [comment]
Hi @trevorlazarus Thanks for the feedback.
I've updated the Python setup instructions (were a bit outdated).
Can you let me know if that works? And: can you paste the error you get in Docker?

**Comment by trevorlazarus** [comment]
Thanks @albertmeronyo for the swift response, will try it out right away and get back to you.

As for the errors, I get no errors whatsoever, I did a docker pull, then a docker-compose up and it seems to be running on 0.0.0.0:8088, but I'm not able to access it.

**Comment by trevorlazarus** [comment]
Is there a way to make the Python setup run on 0.0.0.0:8088 as opposed to 127.0.0.1:8088, I'm not able to access this from outside a Google Compute Engine VM
![screen shot 2016-12-28 at 11 14 19 am](https://cloud.githubusercontent.com/assets/3745470/21519643/38b34ff2-ccef-11e6-8434-8f6c553f06e4.png)

**Comment by trevorlazarus** [comment]
@albertmeronyo, it would be great if you can put out some more instructions for both Docker and Python

**Comment by albertmeronyo** [comment]
@trevorlazarus Thanks for raising this. You can tell flask what host and port you want to use in `src/static.py`. Alternatively (and more securely), you can run grlc via gunicorn and specify host and port in `gunicorn_config.py`

**Comment by albertmeronyo** [comment]
@trevorlazarus I'm assuming this solved your question and closing, let me know otherwise.
