### ISSUE TITLE
"cannot access local variable ‘query_metadata’ where it is not associated with a value"

### ISSUE THREAD

**Issue by bherr2** [CLARIAH/grlc#481]
We have serveral grlc endpoints on our repository here: https://github.com/hubmapconsortium/ccf-grlc which have subdirectories to separate out queries. All of these show the warning message "cannot access local variable ‘query_metadata’ where it is not associated with a value". I've tried to figure out why it shows this, but could not track it down. It doesn't break the queries, but it makes users think the site is broken.

* HRA queries are here:  <https://grlc.io/api-git/hubmapconsortium/ccf-grlc/subdir/hra/>
* HRApop queries are here:  <https://grlc.io/api-git/hubmapconsortium/ccf-grlc/subdir/hra-pop/>
* Ubergraph queries are here: <https://grlc.io/api-git/hubmapconsortium/ccf-grlc/subdir/ubergraph/>
* CCF queries are here:  <https://grlc.io/api-git/hubmapconsortium/ccf-grlc/subdir/ccf/>
* HRA scratch queries are here:  <https://grlc.io/api-git/hubmapconsortium/ccf-grlc/subdir/hra-scratch/>
* Ubergraph scratch queries are here: <https://grlc.io/api-git/hubmapconsortium/ccf-grlc/subdir/ubergraph-scratch/>
* HRA queries for FUSION are here: <https://grlc.io/api-git/hubmapconsortium/ccf-grlc/subdir/fusion/>
* HRA queries for the [Mesh Collision API](https://github.com/hubmapconsortium/hra-tissue-block-annotation) are here: <https://grlc.io/api-git/hubmapconsortium/ccf-grlc/subdir/mesh-collision/>

**Comment by c-martinez** [comment]
Hi @bherr2,

This is definitely a bug. It seems as grlc is trying to process [queries.json](https://github.com/hubmapconsortium/ccf-grlc/blob/main/hra/queries.json) as a [query in json](https://github.com/D2KLab/py-sparql-transformer/tree/master?tab=readme-ov-file#query-in-json), but it is failing to realise it is not a query, and running into an  exception (and not a very clear one).

Will look into it.

**Comment by c-martinez** [comment]
This issue is solved by #487.

Well, I say that, but it is only solved in the `dev` branch and not yet released. I guess we will do a next release soon to fix this, right @albertmeronyo?

In the mean time, it is already working on https://dev.grlc.io/, for example https://dev.grlc.io/api-git/hubmapconsortium/ccf-grlc/subdir/hra/ should work. @bherr2, could you confirm this works for you?

I will close this issue, but please re-open it if necessary.

**Comment by bherr2** [comment]
Works for me, thanks!
