### ISSUE TITLE
Make compatible with Python 3

### ISSUE THREAD

**Issue by dafnevk** [CLARIAH/grlc#53]
The python package `grlc` currently only works in Python 2. It would be nice to also make it compatible with Python 3.

**Comment by rlzijdeman** [comment]
Hi Dafne, I think grlc was purposively developed in Python 2 with the usual Python2 vs python 3 issues [1] in mind. However, grlc can now be run via docker, which should circumvent such issues.

[1] https://wiki.python.org/moin/Python2orPython3
