### ISSUE TITLE
Make upstart run multiple docker containers in a swarm, remove gunicorn

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/grlc#56]

**Comment by LaurensRietveld** [comment]
Have you tried simply running multiple docker containers in a swarm as well? (this is pretty easy as of docker-compose v3)

**Comment by albertmeronyo** [comment]
Good one! And: it would also remove the gunicorn dependency, since worker threading is the only feature grlc uses of it. Thanks @LaurensRietveld !

**Comment by c-martinez** [comment]
I think this is an issue of how you deploy grlc. So perhaps we can just add it as a note on the [developer guidelines](https://github.com/CLARIAH/grlc/blob/master/CONTRIBUTING.md).

I'll  close this issue for now, but please reopen it if it is something we still would like to include.
