### ISSUE TITLE
Check content negotiation in endpoints

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/grlc#58]
Some endpoints have trouble with content negotiation, check e.g. https://data.pdok.nl/sparql
(thanks @reinvantveer)

**Comment by albertmeronyo** [comment]
This works

curl -i "https://data.pdok.nl/sparql?query=select+*+where+%7B%3Fs+%3Fp+%3Fo%7D+limit+10" -H 'Accept: application/json; q=1.0, application/sparql-results+json; q=0.8, text/csv; q=0.1'

While this doesn't 

curl -i "https://data.pdok.nl/sparql?query=select+*+where+%7B%3Fs+%3Fp+%3Fo%7D+limit+10" -H 'Accept: application/json; q=1.0, application/sparql-results+json; q=0.8, text/csv; q=0.1, */*; q=0.1'

So this is a bug at the endpoint's header parsing */* MIME.

**Comment by albertmeronyo** [comment]
Closing since not a grlc's bug (but ambiguous endpoint-side processing)

**Comment by reinvantveer** [comment]
👍
