### ISSUE TITLE
Allow to leave variable unbound in parameterised queries (with dropdown)

### ISSUE THREAD

**Issue by RinkeHoekstra** [CLARIAH/grlc#59]
In some cases, it is inconvenient to have to select a value for a ?_varname_iri parameter: it is better to leave it unbound. An example is where you want to return values for all years, rather than a specific year. 

It would be good to allow users to select a '?' or similar option in the dropdown that makes grlc ignore the specified parameter/variable when rewriting the query. 

Perhaps also return the bindings in the SPARQL results.

**Comment by RinkeHoekstra** [comment]
For queries where the value is not filled in (e.g. not URIs, but literals) it should be possible to specify it as an optional parameter.

**Comment by c-martinez** [comment]
From the API designer point of view, wouldn't it be simpler to have two separate queries (which would translate to two API endpoints), one which return the values of all years, and one which returns values of a specified year only?

I will close this issue, but please reopen if it is still a desired functionality.
