### ISSUE TITLE
problems with basic grlc setting

### ISSUE THREAD

**Issue by ehrmama** [CLARIAH/grlc#63]
Hello,

First of all, thanks for developing this application which sounds really handy.
I am trying to work with it but have some problems, on both public and private instances of grlc.

- **grlc public instance**:

My test [repository](https://github.com/ehrmama/garzoni-queries/tree/master) contains 2 queries, one custom and the other from the [glrc tutorial](https://docs.google.com/document/d/19cvlrfn4h9wdyp0t4DKvt8cS8grUdrkmNg8VvatbegM/edit).

The API seems to work but does not show all queries:
[http://grlc.io/api/ehrmama/garzoni-queries](http://grlc.io/api/ehrmama/garzoni-queries)

One possible source of the pb: grlc does not seem to catch the last commit of github (API-VERSION refers to an old commit). But even if the old commit contains 2 queries, just 1 is shown.

- **grlc local instance**:

I followed the installation instruction with docker. The instance is running (i.e. I can see the home page), but the api/ehrmann/garzoni-query page shows this error:

```

500 : <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p> http://128.178.60.48:8001/api/ehrmama/garzoni-queries/spec
```

And the running instance outputs this message:

```
grlc_1 | 2017-07-10 10:29:54,552 [INFO] (server.swagger_spec) -----> Generating swagger spec for /ehrmama/garzoni-queries on commit None
grlc_1 | 2017-07-10 10:29:55,545 [DEBUG] (prov.init_prov_graph) Ingesting Git2PROV output into RDF graph
grlc_1 | 2017-07-10 10:29:55,634 [INFO] (connectionpool._new_conn) Starting new HTTPS connection (1): api.github.com
grlc_1 | 2017-07-10 10:29:56,091 [DEBUG] (connectionpool._make_request) "GET /repos/ehrmama/garzoni-queries HTTP/1.1" 401 83
grlc_1 | 2017-07-10 10:29:56,097 [INFO] (connectionpool._new_conn) Starting new HTTPS connection (1): api.github.com
grlc_1 | 2017-07-10 10:29:56,494 [DEBUG] (connectionpool._make_request) "GET /repos/ehrmama/garzoni-queries/commits HTTP/1.1" 401 83
grlc_1 | 2017-07-10 10:29:56,498 [ERROR] (app.log_exception) Exception on /api/ehrmama/garzoni-queries/spec [GET]
grlc_1 | Traceback (most recent call last):
grlc_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
grlc_1 |     response = self.full_dispatch_request()
grlc_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
grlc_1 |     rv = self.handle_user_exception(e)
grlc_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
grlc_1 |     reraise(exc_type, exc_value, tb)
grlc_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
grlc_1 |     rv = self.dispatch_request()
grlc_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
grlc_1 |     return self.view_functions[rule.endpoint](**req.view_args)
grlc_1 |   File "/home/grlc/grlc/src/server.py", line 211, in swagger_spec
grlc_1 |     swag = utils.build_swagger_spec(user, repo, sha, static.SERVER_NAME, prov_g)
grlc_1 |   File "/home/grlc/grlc/src/utils.py", line 248, in build_swagger_spec
grlc_1 |     commit_list = [c['sha'] for c in commits]
grlc_1 | TypeError: string indices must be integers
```

The  `on commit None` on the first line seems a bit strange.

I tried with another [repository](https://github.com/barrynl/uncertainty-sparql), but get the exact same error.

Ideally I have quite some queries which I would like to serve from this local instance.

Thanks a lot for your feedback.

**Comment by ehrmama** [comment]
Update: after a while the "example" query is rendered at grlc.io.

**Comment by barrynl** [comment]
Hi, 

I notice you **example** query is working correctly now, only the **test** query does still not show up. 

I think this is caused by a difference in parsing SPARQL by your endpoint at (http://128.178.60.47:8890/sparql) and the parsing done by GRLC. If you change the relevant part of your query to this: 

`SELECT ?year (COUNT (?c) AS ?NbContracts)`

it works correctly (note the additional parenthesis surounding the COUNT expression). It think using the AS keyword requires you to put parenthesis around the whole expression, although in virtuoso this seems optional.

Regards, Barry

**Comment by albertmeronyo** [comment]
I'm assuming @barrynl 's suggestion solved this issue.
@ehrmama let me know otherwise and I'll reopen/investigate. Thanks!

**Comment by ehrmama** [comment]
Hello, yes, sorry for the late reaction (summer in between), the suggestion of @barrynl solved the issue indeed. I ended up parsing all my queries with the same python library as yours in order to validate them (although they were doing fine on virtuoso).
Many thanks for the support and the tool!
