### ISSUE TITLE
time required for grlc to reload new queries

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/grlc#67]
Hi, I just changed my uri's. Github sees the new URI's, but grlc doesn't (by which I mean that if I visit http://grlc.io/api/CLARIAH/wp4-queries-hisco/) I still see the old queries.

Can you add some vague estimate on how long it will take for grlc to 'refresh' or whether this maybe happens just once every 24h?

**Comment by c-martinez** [comment]
grlc downloads queries from the `https://raw.githubusercontent.com/`, and there is some caching going on there. I think it is about 24 hours indeed.

I am guessing that you were trying to update a query more frequently? Was that during a debugging cycle? If so, would a query validation be useful *before* you push your query to github?

**Comment by rlzijdeman** [comment]
Thanks for the response @c-martinez ! I have added this question as a FAQ to the wiki. (Feel free to remove, if you think it's irrelevant).
