### ISSUE TITLE
prefix.txt file with common prefixes to all queries in the repo

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/grlc#7]

**Comment by rlzijdeman** [comment]
a good thing about the current setup is that you can copy paste the entire query and execute it in say yasgui. (the endpoint needs to be specified anyway). if you put part of the prefixes somewhere else, you 'disrupt' that feature

**Comment by c-martinez** [comment]
Agree -- this also makes the query less transparent. Not implementing.
