### ISSUE TITLE
try it out in yasgui instance

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/grlc#71]
Would it be possible that:
- if you click 'try it out' you open an instance of yasgui in which the result is 'run'
- or, because you don't want to people leave the grlc page to add a button 'edit query' which then directs you to yasgui?

Best,

Richard

**Comment by c-martinez** [comment]
Hi Richard,

Could you explain a bit more what do you mean "Try out in Yasgui" ?

**Comment by rlzijdeman** [comment]
Hi @c-martinez sorry for the delay, I've edited my initial comment.

**Comment by c-martinez** [comment]
I see which 'Try it out' button you mean. I don't think that is possible as the page is automatically generated through swagger. Perhaps @albertmeronyo has a different opinion?

**Comment by c-martinez** [comment]
It looks like this feature never got traction. I will close this issue, but please reopen it if necessary.
