### ISSUE TITLE
add download as .csv / excel option

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/grlc#74]
Hi, this one is from the DEMO at the CREATE workshop at UVA (see https://www.slideshare.net/rlzijdeman/grlc-store-share-and-run-sparql-queries). We kind of succeeded in running a grlc flavoured sparql query, without any prior knowledge of github nor SPARQL. However, the 'try-it-out' button only provides part of the output, and people would like to download the result as .CSV. Perhaps something for incorporation with a YASGUI instance?

**Comment by c-martinez** [comment]
Just realized while doing a little bit of cleaning up, this is [already supported](https://github.com/CLARIAH/grlc#features):

*URL-based content negotiation: you can request for specific content types by attaching them to the operation request URL, e.g. http://localhost:8088/CEDAR-project/Queries/residenceStatus_all.csv will request for results in CSV.*
