### ISSUE TITLE
fetch queries that lack summary but do have tags

### ISSUE THREAD

**Issue by rijpma** [CLARIAH/grlc#8]
https://github.com/CLARIAH/wp4-queries/blob/9b3b6dee9e5281dbd72332d6e910fdb79077ccd0/statusbybirtyear_mult.rq would not load while https://github.com/CLARIAH/wp4-queries/blob/3a6bacaca57f6f2c69644546e4a46fdd8622bddc/statusbybirtyear_mult.rq would, even though queries with neither summary nor tags are fetched

**Comment by albertmeronyo** [comment]
@rijpma are these working now? Thanks!

**Comment by albertmeronyo** [comment]
@rijpma The problem is indeed that the first query misses the #+ summary: marker. grlc could ignore such lines, but the fact that the query fails also signals there's something wrong. What would be your preferred behavior?

**Comment by rijpma** [comment]
Mostly I figured that new users would expect their query to show up even if they had a comment on the first line without a summary tag. So the preferred behaviour IMO would then be to fetch and show the query, but not show a summary.

**Comment by albertmeronyo** [comment]
Makes sense, thanks! The next commit fixes it. If the yaml part is invalid (i.e. misses the 'summary:' as in the example) the metadata generation will be skipped, but the query will still show up in the API spec. There's now a log warning message saying as much.
