### ISSUE TITLE
Zenodo DOI for grlc

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/grlc#85]
It is possible to add a DOI for each release of grlc, via [zenodo](https://zenodo.org/). This [guide](https://guides.github.com/activities/citable-code/) shows how to do it. I think this would be a good way to add visibility to grlc (I know for me it would be useful). 

I can take care of adding a DOI, but I would need approval from someone with administrator rights at the CLARIAH github organization level.

@albertmeronyo , @RinkeHoekstra -- what do you think?

**Comment by albertmeronyo** [comment]
That would be great! We need to sync that with the version and release policy in terms of version tags -- also to make it consistent with the version we have in pypi (which I think is pretty old).

Thanks for the idea!

**Comment by c-martinez** [comment]
Good -- I'll request approval and then when we make a new release, we can also update pypi (and maybe check docker image too?)

**Comment by c-martinez** [comment]
Will start the process...
