### ISSUE TITLE
Make use of non-Github, local repositories more sensible

### ISSUE THREAD

**Issue by RinkeHoekstra** [CLARIAH/grlc#90]
For instance:

* URI patterns with `/api/local/local` make no sense
* There should be a way to use grlc without depending on GitHub at all
* There are other VCS' out there that could be useful to support, e.g. GitLab

**Comment by c-martinez** [comment]
Hi @RinkeHoekstra, looking at this just now. Couple of questions:

 - URI `/api/local/local` was added to load grlc queries from local computer -- I found this feature useful to be able to check / modify queries before pushing them to github and to not rely on github. Could you explain a bit more why this doesn't make sense?

 - You are absolutely right about there being other VCS'. Would you know by any chance if Gitlab's API is compatible with Github's API? if yes, then we have instant compatibility. If no, we would need to think how to implement this.

**Comment by c-martinez** [comment]
In [v1.3.3](https://github.com/CLARIAH/grlc/releases/tag/v1.3.3) we introduced [different syntax](https://github.com/CLARIAH/grlc#query-location) to load queries from a GitHub repository (`api-git`), from local storage (`api-local`), and from a specification file (`api-url`), which gives more flexibility on where can queries be located.

I will close this issue, but please repoen it or create a new one if there is more interest on Gitlab support.
