### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by stevencox** [CLARIAH/grlc#92]
Grlc looks awesome.

I'm hitting some rough spots and could use some pointers.

When I create [this repo](https://github.com/stevencox/green-grlc) and point grlc at it, the API UI page, instead of a normal controller name, says "Oh Yeah" and does not present an actual "Try It" endpoint.

What's wrong with my queries?

Also, when I pip install:

* It failed with a permission denied message (see below)
* Couldn't find a package called static (installed manually)
* Then couldn't find a package called gquery (unable to fix)

Thanks again for grlc. It looks great.

Error:
  Running setup.py install for SPARQLWrapper ... done
  Running setup.py install for grlc ... error
    Complete output from command /Users/scox/dev/venv/ckn/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/wt/chtq4vhd41j4wcygw_f9cr980000gp/T/pip-build-gz5p65xe/grlc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/wt/chtq4vhd41j4wcygw_f9cr980000gp/T/pip-tphdstop-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/scox/dev/venv/ckn/include/site/python3.6/grlc:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/grlc
    copying src/__init__.py -> build/lib/grlc
    copying src/cache.py -> build/lib/grlc
    copying src/endpoint.py -> build/lib/grlc
    copying src/gquery.py -> build/lib/grlc
    copying src/server.py -> build/lib/grlc
    copying src/static.py -> build/lib/grlc
    copying src/util.py -> build/lib/grlc
    copying src/utils.py -> build/lib/grlc
    copying src/../../../../../../../../../installer.failurerequests -> build/lib/grlc/../../../../../../../../..
    error: could not create 'build/lib/grlc/../../../../../../../../../installer.failurerequests': Permission denied

**Comment by c-martinez** [comment]
Hi @stevencox,

It seems like you second query works fine, but your first query doesn't show up when I [try to generate an API](http://grlc.io/api/stevencox/green-grlc).

If I interpret your query correctly, you want `?diseaseID` to be an input parameter for your query? In that case, you need to define your parameter using an underscore: `?_diseaseID` (basil syntax). So your query would look like this:
```
#+ summary: First query.
#+ endpoint: http://stars-blazegraph.renci.org/bigdata/sparql
#+ method: GET

prefix drugbank:      <http://chem2bio2rdf.org/drugbank/resource/>
prefix drugbank_drug: <http://chem2bio2rdf.org/drugbank/resource/drugbank_drug/>
prefix ctd:           <http://chem2bio2rdf.org/ctd/resource/>
prefix mesh.disease:  <http://bio2rdf.org/mesh:>

select distinct ?uniprotGeneID where {
  ?dbInter     drugbank:gene               ?uniprotGeneID .
  ?drugID      drugbank:CID                ?pubchemCID.
  ?ctd_disease ctd:diseaseid               ?_diseaseID ;
     ctd:cid                     ?pubchemCID .
}
```

I believe it should work then.

About installation: could you give me a few details about installation? Which platform are you trying to install? I am assuming you are working on a Mac, but I am not sure why it is trying to copy things to that folder...

@albertmeronyo -- do you have any experience with grlc on macs?

**Comment by albertmeronyo** [comment]
Thanks @stevencox !

Your second query works fine, i.e. I get results at http://grlc.io/api/stevencox/green-grlc/second
But grlc cannot generate a spec for your repo because of your first query. Can you try @c-martinez suggestions and report back?

I haven't installed grlc via pip on a mac but will try asap. @stevencox can you confirm? Also, can you try if pip installing in a virtualenv makes any difference?

**Comment by c-martinez** [comment]
Not sure if issue was resolved -- closing. Please re-open if required.
