### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by reinvantveer** [CLARIAH/grlc#93]
Seeing https://github.com/CLARIAH/grlc/blob/0fcf7b629f1b9b34987947c83da066ed6eabb0fe/src/prov.py#L28 the server_name is hardcoded to reference a http address. Our environment is on https, so the browser won't load resources in the OpenAPI spec page on api/{user}/{collection} using the "try it out!" button. The non-https content is blocked.

**Comment by reinvantveer** [comment]
BTW the browser error:
```
Content Security Policy: The page’s settings blocked the loading of a resource at http://grlc.io/api/StanRonzhin/TableauIntegration/PandenVoorBuurt?buurtNaam=Twekkelerveld (“connect-src https://data.labs.pdok.nl https:”).
```

**Comment by c-martinez** [comment]
I believe the line mentioned just causes the provenance trace to say grlc.io runs on http: `<http://grlc.io> a prov:Agent`. It should not affect calls to the sparql endpoint being http or https.

I tried the example query provided, and got a result (and empty set, but the connection to sparql endpoint was successful). The curl command generated was:

```curl -X GET --header "Accept: application/json" "http://grlc.io/api/StanRonzhin/TableauIntegration/PandenVoorBuurt?buurtNaam=Twekkelerveld&endpoint=https%3A%2F%2Fdata.pdok.nl%2Fsparql"```

Closing issue -- please reopen and provide more information if it is still an issue.

**Comment by reinvantveer** [comment]
Hi, no it's still not working from the browser.

To reproduce:
https://data.labs.pdok.nl/api/StanRonzhin/TableauIntegration 
click the second "PandenForBuurt" item, fill in "Twekkelerveld":

``
Content Security Policy: The page’s settings blocked the loading of a resource at http://grlc.io/api/StanRonzhin/TableauIntegration/PandenVoorBuurt?buurtNaam=Twekkelerveld (“connect-src”).
``
This is probably because the api doc/try page is loaded over https where the request is done through http. This cannot be reproduced with a curl call, since it is not issued from the browser.

**Comment by reinvantveer** [comment]
I don't seem to have proper permissions to re-open the issue.

**Comment by c-martinez** [comment]
Ok -- you have your own instance of grlc running over https (I had not understood that part). I think I've figured out what is the issue (and spotted another one):

In `utils.py`, there is a line `swag['schemes'] = [ 'http' ]` which defines how are OpenAPI request's built. You can change that to `swag['schemes'] = ['https']` to make sure calls are always made over https. Or (probably even better) leave it blank (`swag['schemes'] = []`) to make it http or https. I will fix this on the dev branch (if you don't want to wait until that is merged, just edit that line).

The other issue, it seems like your grlc instance is forwarding your requests to `grlc.io` but you probably want to resolve your requests on `data.labs.pdok.nl` (`grlc.io` does not support https). To do this, edit your `config.ini` and set `server_name = data.labs.pdok.nl`.

**Comment by reinvantveer** [comment]
@StanRonzhin we're trying to resolve this issue but it means some downtime on the Tableau web data connector. Are you using it at the moment?

**Comment by StanRonzhin** [comment]
since grlc did not work I used pure sparql to get the data to Tableau in the connector. 
Therefore, I don't use grlc for the moment. but it would be useful to have it at labs.

**Comment by reinvantveer** [comment]
:+1: So I did a fresh pull from grlc. The interface on https://data.labs.pdok.nl/api/StanRonzhin/TableauIntegration is now showing a different error message.
@c-martinez do you recognize this? There is a very elaborate YAMLexception stack trace. I assume it has to do with the way the spec is built and sent to the application. Any ideas on how to fix? Our grlc container isn't logging any errors.

**Comment by c-martinez** [comment]
I think this is due to an issue with the new version of SwaggerUI and the spec being build. I imagine you checked out the master branch? Could you pull the dev branch? That should work (and hopefully we will merge dev to master soon.

**Comment by reinvantveer** [comment]
Thanks, the UI now loads fine, but the requests on https://data.labs.pdok.nl/api/StanRonzhin/TableauIntegration still try to query from https://grlc.io instead of https://data.labs.pdok.nl

The config.ini looks like:
```
[auth]
github_access_token = xxxxxxxxxxxxxxxxxxxxx

[local]
local_sparql_dir = ./

[defaults]
# Default endpoint, if none specified elsewhere
sparql_endpoint = https://data.pdok.nl/sparql
server_name = data.labs.pdok.nl
user = none     # endpoint default authentication
password = none
```

So, looks like we're nearly there, but not quite!

**Comment by c-martinez** [comment]
Ok, getting closer...

Out of curiosity: how are you starting your grlc instance? docker?

**Comment by reinvantveer** [comment]
Yes. The contents are added to the container during build.

**Comment by c-martinez** [comment]
I see -- the issue was that the server name was not configurable on the docker image -- latest dev version fixes this. Could you try it out?

If possible, make sure it works, maybe a good idea to remove docker images (`docker rm grlc_grlc_1` and `docker rmi clariah/grlc`) to avoid it using a docker image from a previous build.

**Comment by reinvantveer** [comment]
Yes, that did it!
@StanRonzhin can you see why the queries are not returning any results? Is it due to some error in the query?

**Comment by c-martinez** [comment]
Great! Good to know. I'll close this issue then.

I was not sure if you needed to remove the images, but I usually do just to be sure.
